final culottes_list = [
  {"item-id": "2525612_12", "type": " culottes", "fake-name": "trendy whimsical futuristic edgy culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2902365_8", "type": " culottes", "fake-name": "stylish cozy mellow contemporary culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2364723_4", "type": " culottes", "fake-name": "striking dynamic sharp whimsical culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2491997_20", "type": " culottes", "fake-name": "sophisticated playful refined urbane culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2902365_16", "type": " culottes", "fake-name": "sleek urban sleek sleek culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2209432_4", "type": " culottes", "fake-name": "classy vintage zen versatile culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2147316_8", "type": " culottes", "fake-name": "elegant vibrant wholesome serene culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2525612_16", "type": " culottes", "fake-name": "sleek urban sleek sleek culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2385710_12", "type": " culottes", "fake-name": "sophisticated playful refined urbane culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2209432_4", "type": " culottes", "fake-name": "classy vintage zen versatile culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2525612_8", "type": " culottes", "fake-name": "chic casual eclectic opulent culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2549740_20", "type": " culottes", "fake-name": "dapper eclectic graceful radiant culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2359988_12", "type": " culottes", "fake-name": "chic casual eclectic opulent culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2147316_8", "type": " culottes", "fake-name": "elegant vibrant wholesome serene culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2549740_20", "type": " culottes", "fake-name": "dapper eclectic graceful radiant culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2305964_1", "type": " culottes", "fake-name": "sophisticated playful refined urbane culottes", "image-path": "asset/clothes/ culottes/2.jpeg"},
  {"item-id": "2005822_8", "type": " culottes", "fake-name": "stylish cozy mellow contemporary culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2377735_14", "type": " culottes", "fake-name": "polished bohemian blissful organic culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2113614_8", "type": " culottes", "fake-name": "striking dynamic sharp whimsical culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2209432_8", "type": " culottes", "fake-name": "trendy whimsical futuristic edgy culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2624292_8", "type": " culottes", "fake-name": "elegant vibrant wholesome serene culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2113614_20", "type": " culottes", "fake-name": "posh ethereal regal ethereal culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2005822_8", "type": " culottes", "fake-name": "stylish cozy mellow contemporary culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2209432_14", "type": " culottes", "fake-name": "elegant vibrant wholesome serene culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2902365_8", "type": " culottes", "fake-name": "stylish cozy mellow contemporary culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2377735_8", "type": " culottes", "fake-name": "glamorous minimalist urban bohemian culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2549740_4", "type": " culottes", "fake-name": "sleek urban sleek sleek culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {
    "item-id": "2364723_1",
    "type": " culottes",
    "fake-name": "exquisite posh spontaneous trendsetting culottes",
    "image-path": "asset/clothes/ culottes/4.jpeg"
  },
  {"item-id": "2209432_14", "type": " culottes", "fake-name": "elegant vibrant wholesome serene culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2209432_14", "type": " culottes", "fake-name": "elegant vibrant wholesome serene culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2902365_4", "type": " culottes", "fake-name": "elegant vibrant wholesome serene culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2525612_4", "type": " culottes", "fake-name": "fashionable relaxed lively poised culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2377735_8", "type": " culottes", "fake-name": "glamorous minimalist urban bohemian culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2525612_4", "type": " culottes", "fake-name": "fashionable relaxed lively poised culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2113614_4", "type": " culottes", "fake-name": "glamorous minimalist urban bohemian culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2834294_4", "type": " culottes", "fake-name": "dapper eclectic graceful radiant culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2491997_8", "type": " culottes", "fake-name": "elegant vibrant wholesome serene culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2834294_8", "type": " culottes", "fake-name": "elegant vibrant wholesome serene culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2364723_8", "type": " culottes", "fake-name": "dapper eclectic graceful radiant culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2305964_12", "type": " culottes", "fake-name": "sophisticated playful refined urbane culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2834294_8", "type": " culottes", "fake-name": "elegant vibrant wholesome serene culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2005822_16", "type": " culottes", "fake-name": "stylish cozy mellow contemporary culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2549740_12", "type": " culottes", "fake-name": "sophisticated playful refined urbane culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {
    "item-id": "2005822_20",
    "type": " culottes",
    "fake-name": "contemporary quirky free-spirited refined culottes",
    "image-path": "asset/clothes/ culottes/1.jpeg"
  },
  {"item-id": "2549740_16", "type": " culottes", "fake-name": "polished bohemian blissful organic culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2525612_1", "type": " culottes", "fake-name": "dapper eclectic graceful radiant culottes", "image-path": "asset/clothes/ culottes/2.jpeg"},
  {
    "item-id": "2491997_4",
    "type": " culottes",
    "fake-name": "exquisite posh spontaneous trendsetting culottes",
    "image-path": "asset/clothes/ culottes/3.jpeg"
  },
  {"item-id": "2209432_4", "type": " culottes", "fake-name": "classy vintage zen versatile culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2147316_8", "type": " culottes", "fake-name": "elegant vibrant wholesome serene culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2834294_8", "type": " culottes", "fake-name": "elegant vibrant wholesome serene culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2305964_12", "type": " culottes", "fake-name": "sophisticated playful refined urbane culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2624292_20", "type": " culottes", "fake-name": "glamorous minimalist urban bohemian culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2209432_20", "type": " culottes", "fake-name": "sophisticated playful refined urbane culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2147316_12", "type": " culottes", "fake-name": "polished bohemian blissful organic culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {
    "item-id": "2005822_20",
    "type": " culottes",
    "fake-name": "contemporary quirky free-spirited refined culottes",
    "image-path": "asset/clothes/ culottes/1.jpeg"
  },
  {"item-id": "2005822_12", "type": " culottes", "fake-name": "polished bohemian blissful organic culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2549740_8", "type": " culottes", "fake-name": "glamorous minimalist urban bohemian culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2525612_24", "type": " culottes", "fake-name": "chic casual eclectic opulent culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2902365_8", "type": " culottes", "fake-name": "stylish cozy mellow contemporary culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2834294_14", "type": " culottes", "fake-name": "stylish cozy mellow contemporary culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2385710_12", "type": " culottes", "fake-name": "sophisticated playful refined urbane culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {
    "item-id": "2005822_20",
    "type": " culottes",
    "fake-name": "contemporary quirky free-spirited refined culottes",
    "image-path": "asset/clothes/ culottes/1.jpeg"
  },
  {"item-id": "2902365_20", "type": " culottes", "fake-name": "classy vintage zen versatile culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {
    "item-id": "2005822_20",
    "type": " culottes",
    "fake-name": "contemporary quirky free-spirited refined culottes",
    "image-path": "asset/clothes/ culottes/1.jpeg"
  },
  {"item-id": "2549740_1", "type": " culottes", "fake-name": "classy vintage zen versatile culottes", "image-path": "asset/clothes/ culottes/2.jpeg"},
  {"item-id": "2549740_8", "type": " culottes", "fake-name": "glamorous minimalist urban bohemian culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2147316_20", "type": " culottes", "fake-name": "sophisticated playful refined urbane culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2005822_4", "type": " culottes", "fake-name": "posh ethereal regal ethereal culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2834294_8", "type": " culottes", "fake-name": "elegant vibrant wholesome serene culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2525612_8", "type": " culottes", "fake-name": "chic casual eclectic opulent culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2005822_16", "type": " culottes", "fake-name": "stylish cozy mellow contemporary culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2525612_8", "type": " culottes", "fake-name": "chic casual eclectic opulent culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2377735_14", "type": " culottes", "fake-name": "polished bohemian blissful organic culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2377735_14", "type": " culottes", "fake-name": "polished bohemian blissful organic culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2834294_14", "type": " culottes", "fake-name": "stylish cozy mellow contemporary culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2549740_20", "type": " culottes", "fake-name": "dapper eclectic graceful radiant culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2364723_4", "type": " culottes", "fake-name": "striking dynamic sharp whimsical culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2209432_14", "type": " culottes", "fake-name": "elegant vibrant wholesome serene culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2209432_8", "type": " culottes", "fake-name": "trendy whimsical futuristic edgy culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2209432_8", "type": " culottes", "fake-name": "trendy whimsical futuristic edgy culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2147316_8", "type": " culottes", "fake-name": "elegant vibrant wholesome serene culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {
    "item-id": "2305964_8",
    "type": " culottes",
    "fake-name": "contemporary quirky free-spirited refined culottes",
    "image-path": "asset/clothes/ culottes/1.jpeg"
  },
  {"item-id": "2834294_20", "type": " culottes", "fake-name": "sleek urban sleek sleek culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2359988_12", "type": " culottes", "fake-name": "chic casual eclectic opulent culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2209432_14", "type": " culottes", "fake-name": "elegant vibrant wholesome serene culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2834294_20", "type": " culottes", "fake-name": "sleek urban sleek sleek culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2834294_4", "type": " culottes", "fake-name": "dapper eclectic graceful radiant culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2005822_16", "type": " culottes", "fake-name": "stylish cozy mellow contemporary culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2005822_12", "type": " culottes", "fake-name": "polished bohemian blissful organic culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2209432_20", "type": " culottes", "fake-name": "sophisticated playful refined urbane culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2902365_1", "type": " culottes", "fake-name": "posh ethereal regal ethereal culottes", "image-path": "asset/clothes/ culottes/4.jpeg"},
  {"item-id": "2624292_8", "type": " culottes", "fake-name": "elegant vibrant wholesome serene culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2005822_24", "type": " culottes", "fake-name": "classy vintage zen versatile culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2902365_12", "type": " culottes", "fake-name": "sophisticated playful refined urbane culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2147316_24", "type": " culottes", "fake-name": "sleek urban sleek sleek culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2491997_20", "type": " culottes", "fake-name": "sophisticated playful refined urbane culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2305964_1", "type": " culottes", "fake-name": "sophisticated playful refined urbane culottes", "image-path": "asset/clothes/ culottes/2.jpeg"},
  {"item-id": "2549740_20", "type": " culottes", "fake-name": "dapper eclectic graceful radiant culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2005822_8", "type": " culottes", "fake-name": "stylish cozy mellow contemporary culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2364723_4", "type": " culottes", "fake-name": "striking dynamic sharp whimsical culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2549740_8", "type": " culottes", "fake-name": "glamorous minimalist urban bohemian culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2902365_1", "type": " culottes", "fake-name": "posh ethereal regal ethereal culottes", "image-path": "asset/clothes/ culottes/4.jpeg"},
  {"item-id": "2549740_20", "type": " culottes", "fake-name": "dapper eclectic graceful radiant culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2834294_4", "type": " culottes", "fake-name": "dapper eclectic graceful radiant culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2525612_1", "type": " culottes", "fake-name": "dapper eclectic graceful radiant culottes", "image-path": "asset/clothes/ culottes/2.jpeg"},
  {"item-id": "2525612_16", "type": " culottes", "fake-name": "sleek urban sleek sleek culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2549740_4", "type": " culottes", "fake-name": "sleek urban sleek sleek culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2549740_24", "type": " culottes", "fake-name": "edgy radiant dynamic exuberant culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2209432_20", "type": " culottes", "fake-name": "sophisticated playful refined urbane culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2525612_4", "type": " culottes", "fake-name": "fashionable relaxed lively poised culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2209432_14", "type": " culottes", "fake-name": "elegant vibrant wholesome serene culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2525612_8", "type": " culottes", "fake-name": "chic casual eclectic opulent culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2902365_20", "type": " culottes", "fake-name": "classy vintage zen versatile culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2005822_12", "type": " culottes", "fake-name": "polished bohemian blissful organic culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2305964_1", "type": " culottes", "fake-name": "sophisticated playful refined urbane culottes", "image-path": "asset/clothes/ culottes/2.jpeg"},
  {
    "item-id": "2364723_1",
    "type": " culottes",
    "fake-name": "exquisite posh spontaneous trendsetting culottes",
    "image-path": "asset/clothes/ culottes/4.jpeg"
  },
  {"item-id": "2364723_12", "type": " culottes", "fake-name": "striking dynamic sharp whimsical culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2525612_4", "type": " culottes", "fake-name": "fashionable relaxed lively poised culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2902365_12", "type": " culottes", "fake-name": "sophisticated playful refined urbane culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2491997_8", "type": " culottes", "fake-name": "elegant vibrant wholesome serene culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2005822_8", "type": " culottes", "fake-name": "stylish cozy mellow contemporary culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2005822_4", "type": " culottes", "fake-name": "posh ethereal regal ethereal culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2005822_8", "type": " culottes", "fake-name": "stylish cozy mellow contemporary culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2902365_20", "type": " culottes", "fake-name": "classy vintage zen versatile culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {
    "item-id": "2005822_20",
    "type": " culottes",
    "fake-name": "contemporary quirky free-spirited refined culottes",
    "image-path": "asset/clothes/ culottes/1.jpeg"
  },
  {"item-id": "2305964_16", "type": " culottes", "fake-name": "sophisticated playful refined urbane culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {
    "item-id": "2005822_20",
    "type": " culottes",
    "fake-name": "contemporary quirky free-spirited refined culottes",
    "image-path": "asset/clothes/ culottes/1.jpeg"
  },
  {"item-id": "2549740_20", "type": " culottes", "fake-name": "dapper eclectic graceful radiant culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2525612_24", "type": " culottes", "fake-name": "chic casual eclectic opulent culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2525612_16", "type": " culottes", "fake-name": "sleek urban sleek sleek culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2834294_14", "type": " culottes", "fake-name": "stylish cozy mellow contemporary culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2902365_12", "type": " culottes", "fake-name": "sophisticated playful refined urbane culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2364723_8", "type": " culottes", "fake-name": "dapper eclectic graceful radiant culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2834294_14", "type": " culottes", "fake-name": "stylish cozy mellow contemporary culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2902365_4", "type": " culottes", "fake-name": "elegant vibrant wholesome serene culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2209432_8", "type": " culottes", "fake-name": "trendy whimsical futuristic edgy culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2147316_16", "type": " culottes", "fake-name": "trendy whimsical futuristic edgy culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2209432_8", "type": " culottes", "fake-name": "trendy whimsical futuristic edgy culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2525612_12", "type": " culottes", "fake-name": "trendy whimsical futuristic edgy culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2005822_1", "type": " culottes", "fake-name": "chic casual eclectic opulent culottes", "image-path": "asset/clothes/ culottes/2.jpeg"},
  {"item-id": "2902365_20", "type": " culottes", "fake-name": "classy vintage zen versatile culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2525612_20", "type": " culottes", "fake-name": "striking dynamic sharp whimsical culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2113614_4", "type": " culottes", "fake-name": "glamorous minimalist urban bohemian culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2549740_16", "type": " culottes", "fake-name": "polished bohemian blissful organic culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2005822_12", "type": " culottes", "fake-name": "polished bohemian blissful organic culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2525612_1", "type": " culottes", "fake-name": "dapper eclectic graceful radiant culottes", "image-path": "asset/clothes/ culottes/2.jpeg"},
  {"item-id": "2525612_4", "type": " culottes", "fake-name": "fashionable relaxed lively poised culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2377735_4", "type": " culottes", "fake-name": "sleek urban sleek sleek culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2209432_4", "type": " culottes", "fake-name": "classy vintage zen versatile culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2834294_4", "type": " culottes", "fake-name": "dapper eclectic graceful radiant culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2377735_14", "type": " culottes", "fake-name": "polished bohemian blissful organic culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2377735_20", "type": " culottes", "fake-name": "polished bohemian blissful organic culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2525612_24", "type": " culottes", "fake-name": "chic casual eclectic opulent culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2549740_24", "type": " culottes", "fake-name": "edgy radiant dynamic exuberant culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2209432_4", "type": " culottes", "fake-name": "classy vintage zen versatile culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2902365_4", "type": " culottes", "fake-name": "elegant vibrant wholesome serene culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {
    "item-id": "2491997_4",
    "type": " culottes",
    "fake-name": "exquisite posh spontaneous trendsetting culottes",
    "image-path": "asset/clothes/ culottes/3.jpeg"
  },
  {"item-id": "2525612_8", "type": " culottes", "fake-name": "chic casual eclectic opulent culottes", "image-path": "asset/clothes/ culottes/1.jpeg"},
  {"item-id": "2209432_14", "type": " culottes", "fake-name": "elegant vibrant wholesome serene culottes", "image-path": "asset/clothes/ culottes/3.jpeg"},
  {"item-id": "2005822_16", "type": " culottes", "fake-name": "stylish cozy mellow contemporary culottes", "image-path": "asset/clothes/ culottes/1.jpeg"}
];
