final cardigan_list = [
  {"item-id": "2722297", "type": "cardigan", "fake-name": "elegant playful spontaneous trendsetting cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "trendy dynamic wholesome opulent cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2494511", "type": "cardigan", "fake-name": "contemporary ethereal lively versatile cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2299144", "type": "cardigan", "fake-name": "elegant relaxed free-spirited urbane cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {
    "item-id": "2509818",
    "type": "cardigan",
    "fake-name": "sophisticated whimsical spontaneous trendsetting cardigan",
    "image-path": "asset/clothes/cardigan/3.jpeg"
  },
  {"item-id": "2521310", "type": "cardigan", "fake-name": "radiant casual graceful bohemian cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2951824", "type": "cardigan", "fake-name": "posh cozy sleek urbane cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2722297", "type": "cardigan", "fake-name": "classy bohemian urban refined cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "sleek eclectic mellow opulent cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {
    "item-id": "2521310",
    "type": "cardigan",
    "fake-name": "contemporary eclectic free-spirited opulent cardigan",
    "image-path": "asset/clothes/cardigan/3.jpeg"
  },
  {"item-id": "2144424", "type": "cardigan", "fake-name": "edgy urban eclectic refined cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2743996", "type": "cardigan", "fake-name": "glamorous eclectic ethereal versatile cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2127264", "type": "cardigan", "fake-name": "polished casual dynamic trendsetting cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2071468", "type": "cardigan", "fake-name": "posh relaxed wholesome effortless cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2766308", "type": "cardigan", "fake-name": "polished ethereal spontaneous ethereal cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "glamorous casual ethereal opulent cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2144424", "type": "cardigan", "fake-name": "sleek vintage dynamic edgy cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "stylish dynamic eclectic urbane cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2094264", "type": "cardigan", "fake-name": "elegant relaxed eclectic poised cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "elegant vibrant mellow edgy cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2029039", "type": "cardigan", "fake-name": "polished vibrant free-spirited ethereal cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2743996", "type": "cardigan", "fake-name": "exquisite relaxed dynamic serene cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2509818", "type": "cardigan", "fake-name": "contemporary eclectic magnetic suave cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2299144", "type": "cardigan", "fake-name": "sleek radiant mellow serene cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2029039", "type": "cardigan", "fake-name": "sleek relaxed blissful refined cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2065252", "type": "cardigan", "fake-name": "elegant radiant futuristic exuberant cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2766308", "type": "cardigan", "fake-name": "stylish ethereal refined trendsetting cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2261101", "type": "cardigan", "fake-name": "posh minimalist regal contemporary cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "exquisite vintage sharp ethereal cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "posh vintage spontaneous serene cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2029039", "type": "cardigan", "fake-name": "radiant ethereal graceful refined cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2082039", "type": "cardigan", "fake-name": "classy vibrant wholesome effortless cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2743996", "type": "cardigan", "fake-name": "classy posh free-spirited effortless cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "trendy casual wholesome bohemian cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "posh bohemian futuristic sleek cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2144424", "type": "cardigan", "fake-name": "elegant bohemian blissful refined cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2743996", "type": "cardigan", "fake-name": "fashionable minimalist wholesome urbane cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2144424", "type": "cardigan", "fake-name": "fashionable radiant spontaneous opulent cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2299144", "type": "cardigan", "fake-name": "polished cozy futuristic effortless cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2299144", "type": "cardigan", "fake-name": "chic quirky spontaneous sleek cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "dapper radiant eclectic contemporary cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2082039", "type": "cardigan", "fake-name": "dapper casual mellow effortless cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2509818", "type": "cardigan", "fake-name": "radiant bohemian sleek ethereal cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "fashionable vintage futuristic opulent cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2029039", "type": "cardigan", "fake-name": "polished playful ethereal organic cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2261101", "type": "cardigan", "fake-name": "exquisite radiant regal contemporary cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2621527", "type": "cardigan", "fake-name": "polished vintage wholesome opulent cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2494511", "type": "cardigan", "fake-name": "sleek casual urban exuberant cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2743996", "type": "cardigan", "fake-name": "sophisticated ethereal eclectic radiant cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2509818", "type": "cardigan", "fake-name": "chic eclectic dynamic radiant cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "dapper vintage eclectic radiant cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2743996", "type": "cardigan", "fake-name": "stylish posh blissful ethereal cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2065252", "type": "cardigan", "fake-name": "polished minimalist spontaneous sleek cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2127264", "type": "cardigan", "fake-name": "trendy ethereal free-spirited effortless cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "radiant quirky eclectic edgy cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {
    "item-id": "2521310",
    "type": "cardigan",
    "fake-name": "contemporary relaxed futuristic contemporary cardigan",
    "image-path": "asset/clothes/cardigan/3.jpeg"
  },
  {"item-id": "2509818", "type": "cardigan", "fake-name": "polished minimalist lively trendsetting cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2743996", "type": "cardigan", "fake-name": "posh vibrant eclectic edgy cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2299144", "type": "cardigan", "fake-name": "trendy whimsical mellow radiant cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "posh radiant futuristic opulent cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "alluring dynamic refined effortless cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2555454", "type": "cardigan", "fake-name": "striking posh lively opulent cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "elegant vintage spontaneous sleek cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2144424", "type": "cardigan", "fake-name": "chic casual ethereal whimsical cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2127264", "type": "cardigan", "fake-name": "fashionable eclectic sleek versatile cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2538397", "type": "cardigan", "fake-name": "sophisticated casual ethereal whimsical cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2144424", "type": "cardigan", "fake-name": "trendy minimalist zen serene cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "radiant cozy dynamic urbane cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2127264", "type": "cardigan", "fake-name": "posh cozy eclectic effortless cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2555454", "type": "cardigan", "fake-name": "radiant vintage sleek urbane cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2029039", "type": "cardigan", "fake-name": "glamorous casual ethereal bohemian cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2144424", "type": "cardigan", "fake-name": "dapper dynamic magnetic serene cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2127264", "type": "cardigan", "fake-name": "contemporary dynamic blissful refined cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "edgy vintage spontaneous refined cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "exquisite ethereal magnetic poised cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2633784", "type": "cardigan", "fake-name": "classy minimalist magnetic refined cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2766308", "type": "cardigan", "fake-name": "dapper relaxed graceful versatile cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2127264", "type": "cardigan", "fake-name": "edgy whimsical graceful effortless cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "elegant radiant magnetic effortless cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2509818", "type": "cardigan", "fake-name": "dapper relaxed mellow poised cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2615236", "type": "cardigan", "fake-name": "striking vintage urban exuberant cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2029039", "type": "cardigan", "fake-name": "glamorous quirky futuristic sleek cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "sleek casual regal edgy cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2494511", "type": "cardigan", "fake-name": "classy bohemian dynamic bohemian cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2555454", "type": "cardigan", "fake-name": "sophisticated minimalist magnetic suave cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2766308", "type": "cardigan", "fake-name": "sleek bohemian lively radiant cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2615236", "type": "cardigan", "fake-name": "sleek radiant ethereal sleek cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2144424", "type": "cardigan", "fake-name": "stylish whimsical zen versatile cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "sleek bohemian ethereal sleek cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "chic playful wholesome serene cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2722297", "type": "cardigan", "fake-name": "fashionable playful spontaneous edgy cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2603249", "type": "cardigan", "fake-name": "chic vibrant free-spirited organic cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "exquisite casual urban poised cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2621527", "type": "cardigan", "fake-name": "trendy vintage regal edgy cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "sleek eclectic free-spirited effortless cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2299144", "type": "cardigan", "fake-name": "glamorous casual wholesome edgy cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2144424", "type": "cardigan", "fake-name": "elegant dynamic lively radiant cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "chic urban magnetic versatile cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "edgy vintage eclectic edgy cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2144424", "type": "cardigan", "fake-name": "sleek casual lively whimsical cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2743996", "type": "cardigan", "fake-name": "fashionable urban urban whimsical cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2082039", "type": "cardigan", "fake-name": "contemporary vintage eclectic ethereal cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2633784", "type": "cardigan", "fake-name": "radiant whimsical lively contemporary cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2144424", "type": "cardigan", "fake-name": "contemporary dynamic urban suave cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "glamorous minimalist blissful poised cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2766308", "type": "cardigan", "fake-name": "posh ethereal magnetic suave cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "trendy vibrant sharp exuberant cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2144424", "type": "cardigan", "fake-name": "glamorous relaxed wholesome whimsical cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "fashionable dynamic futuristic poised cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2603249", "type": "cardigan", "fake-name": "exquisite radiant wholesome opulent cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2127264", "type": "cardigan", "fake-name": "chic playful refined sleek cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2053422", "type": "cardigan", "fake-name": "sleek radiant lively trendsetting cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2144424", "type": "cardigan", "fake-name": "exquisite posh magnetic organic cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2144424", "type": "cardigan", "fake-name": "sleek vintage magnetic trendsetting cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "posh urban futuristic bohemian cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2494511", "type": "cardigan", "fake-name": "classy whimsical lively suave cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2766308", "type": "cardigan", "fake-name": "fashionable quirky sharp trendsetting cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2494511", "type": "cardigan", "fake-name": "alluring quirky dynamic versatile cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "sophisticated radiant mellow serene cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "trendy vibrant dynamic trendsetting cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2615236", "type": "cardigan", "fake-name": "chic eclectic dynamic contemporary cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2261101", "type": "cardigan", "fake-name": "trendy radiant futuristic exuberant cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "fashionable whimsical mellow opulent cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2621527", "type": "cardigan", "fake-name": "posh urban eclectic trendsetting cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "polished relaxed magnetic serene cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "chic quirky zen bohemian cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2509818", "type": "cardigan", "fake-name": "edgy quirky blissful whimsical cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "glamorous quirky eclectic opulent cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2299144", "type": "cardigan", "fake-name": "glamorous cozy spontaneous versatile cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2722297", "type": "cardigan", "fake-name": "posh casual futuristic suave cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "elegant cozy graceful opulent cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2494511", "type": "cardigan", "fake-name": "posh casual regal whimsical cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2127264", "type": "cardigan", "fake-name": "chic bohemian eclectic refined cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2743996", "type": "cardigan", "fake-name": "striking whimsical eclectic refined cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2127264", "type": "cardigan", "fake-name": "polished relaxed regal refined cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "glamorous eclectic graceful exuberant cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "striking relaxed graceful radiant cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "alluring dynamic mellow effortless cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "striking vibrant eclectic exuberant cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2082039", "type": "cardigan", "fake-name": "glamorous vintage urban organic cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2065252", "type": "cardigan", "fake-name": "alluring radiant mellow suave cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "radiant cozy blissful sleek cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2766308", "type": "cardigan", "fake-name": "dapper urban magnetic opulent cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "radiant casual magnetic ethereal cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2603249", "type": "cardigan", "fake-name": "alluring vintage dynamic poised cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2082039", "type": "cardigan", "fake-name": "contemporary urban free-spirited sleek cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2722297", "type": "cardigan", "fake-name": "striking casual free-spirited poised cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "striking urban free-spirited exuberant cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "exquisite minimalist graceful suave cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2538397", "type": "cardigan", "fake-name": "contemporary ethereal urban contemporary cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "trendy cozy magnetic trendsetting cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2603249", "type": "cardigan", "fake-name": "fashionable vintage blissful organic cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "trendy cozy magnetic refined cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2930997", "type": "cardigan", "fake-name": "sophisticated casual mellow urbane cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2029039", "type": "cardigan", "fake-name": "chic posh sleek poised cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2029039", "type": "cardigan", "fake-name": "dapper vintage sleek sleek cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2743996", "type": "cardigan", "fake-name": "stylish radiant ethereal serene cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2029039", "type": "cardigan", "fake-name": "polished vibrant blissful organic cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2611913", "type": "cardigan", "fake-name": "alluring relaxed regal organic cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "contemporary playful futuristic ethereal cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "fashionable quirky zen radiant cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2094264", "type": "cardigan", "fake-name": "striking quirky wholesome poised cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "dapper cozy free-spirited versatile cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {
    "item-id": "2521310",
    "type": "cardigan",
    "fake-name": "fashionable cozy free-spirited trendsetting cardigan",
    "image-path": "asset/clothes/cardigan/3.jpeg"
  },
  {"item-id": "2029039", "type": "cardigan", "fake-name": "polished posh sharp suave cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "radiant playful zen serene cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2494511", "type": "cardigan", "fake-name": "exquisite dynamic urban serene cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "elegant casual zen refined cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2299144", "type": "cardigan", "fake-name": "dapper posh zen bohemian cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2509818", "type": "cardigan", "fake-name": "radiant cozy free-spirited ethereal cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "stylish cozy graceful urbane cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2299144", "type": "cardigan", "fake-name": "dapper playful blissful edgy cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "radiant bohemian refined whimsical cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "glamorous minimalist graceful serene cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2071468", "type": "cardigan", "fake-name": "sophisticated vintage regal refined cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2509818", "type": "cardigan", "fake-name": "radiant ethereal sleek suave cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2029039", "type": "cardigan", "fake-name": "striking quirky blissful versatile cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2144424", "type": "cardigan", "fake-name": "exquisite minimalist wholesome ethereal cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "sleek eclectic free-spirited refined cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2029039", "type": "cardigan", "fake-name": "radiant radiant eclectic opulent cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2127264", "type": "cardigan", "fake-name": "contemporary cozy futuristic opulent cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2603249", "type": "cardigan", "fake-name": "sleek quirky magnetic sleek cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2615236", "type": "cardigan", "fake-name": "elegant relaxed refined sleek cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2743996", "type": "cardigan", "fake-name": "chic cozy graceful whimsical cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2509818", "type": "cardigan", "fake-name": "edgy posh magnetic whimsical cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "elegant ethereal regal radiant cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2665956", "type": "cardigan", "fake-name": "radiant radiant wholesome whimsical cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2029039", "type": "cardigan", "fake-name": "dapper eclectic urban bohemian cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "trendy vibrant ethereal urbane cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2029039", "type": "cardigan", "fake-name": "glamorous whimsical zen organic cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2509818", "type": "cardigan", "fake-name": "classy dynamic dynamic edgy cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2722297", "type": "cardigan", "fake-name": "elegant radiant zen contemporary cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2951824", "type": "cardigan", "fake-name": "exquisite dynamic urban radiant cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2509818", "type": "cardigan", "fake-name": "polished cozy magnetic whimsical cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2094264", "type": "cardigan", "fake-name": "striking ethereal free-spirited whimsical cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2261101", "type": "cardigan", "fake-name": "elegant posh ethereal ethereal cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "contemporary ethereal zen trendsetting cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "exquisite ethereal magnetic radiant cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2144424", "type": "cardigan", "fake-name": "trendy vibrant mellow refined cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "trendy casual eclectic versatile cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "sophisticated radiant lively opulent cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "sophisticated quirky mellow edgy cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2029039", "type": "cardigan", "fake-name": "contemporary whimsical blissful edgy cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2615236", "type": "cardigan", "fake-name": "polished playful refined organic cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2299144", "type": "cardigan", "fake-name": "glamorous whimsical blissful poised cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2633784", "type": "cardigan", "fake-name": "sleek casual mellow urbane cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {
    "item-id": "2494511",
    "type": "cardigan",
    "fake-name": "fashionable playful futuristic trendsetting cardigan",
    "image-path": "asset/clothes/cardigan/4.jpeg"
  },
  {"item-id": "2603249", "type": "cardigan", "fake-name": "stylish bohemian refined radiant cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2127264", "type": "cardigan", "fake-name": "exquisite ethereal graceful ethereal cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2299144", "type": "cardigan", "fake-name": "sophisticated casual lively bohemian cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "contemporary vintage futuristic suave cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2299144", "type": "cardigan", "fake-name": "sleek relaxed futuristic trendsetting cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2127264", "type": "cardigan", "fake-name": "sleek quirky graceful whimsical cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2538397", "type": "cardigan", "fake-name": "glamorous playful free-spirited urbane cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2144424", "type": "cardigan", "fake-name": "edgy cozy lively effortless cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2743996", "type": "cardigan", "fake-name": "radiant playful sharp trendsetting cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2029039", "type": "cardigan", "fake-name": "striking eclectic blissful opulent cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2127264", "type": "cardigan", "fake-name": "posh quirky dynamic serene cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "glamorous quirky ethereal sleek cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2144424", "type": "cardigan", "fake-name": "trendy playful dynamic organic cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2633784", "type": "cardigan", "fake-name": "edgy urban sleek trendsetting cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2611913", "type": "cardigan", "fake-name": "classy relaxed spontaneous opulent cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2603249", "type": "cardigan", "fake-name": "alluring urban dynamic trendsetting cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2127264", "type": "cardigan", "fake-name": "contemporary bohemian magnetic opulent cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "trendy bohemian regal refined cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "trendy radiant spontaneous refined cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2494511", "type": "cardigan", "fake-name": "posh whimsical spontaneous trendsetting cardigan", "image-path": "asset/clothes/cardigan/4.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "striking posh mellow opulent cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "classy ethereal magnetic versatile cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "classy radiant sleek organic cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "elegant posh graceful trendsetting cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2743996", "type": "cardigan", "fake-name": "chic posh regal trendsetting cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "trendy dynamic ethereal serene cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2065252", "type": "cardigan", "fake-name": "fashionable ethereal wholesome ethereal cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2262637", "type": "cardigan", "fake-name": "contemporary bohemian graceful effortless cardigan", "image-path": "asset/clothes/cardigan/2.jpeg"},
  {"item-id": "2509818", "type": "cardigan", "fake-name": "classy whimsical regal urbane cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "elegant casual futuristic sleek cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2521310", "type": "cardigan", "fake-name": "classy playful sleek whimsical cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2127264", "type": "cardigan", "fake-name": "edgy bohemian blissful ethereal cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2555454", "type": "cardigan", "fake-name": "stylish ethereal free-spirited versatile cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2509818", "type": "cardigan", "fake-name": "striking vibrant futuristic ethereal cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"}
];
