final cardigan_list = [
  {"item-id": "2722297_4", "type": "cardigan", "fake-name": "sophisticated playful refined urbane cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2262637_4", "type": "cardigan", "fake-name": "glamorous minimalist urban bohemian cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2494511_14", "type": "cardigan", "fake-name": "glamorous minimalist urban bohemian cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2509818_14", "type": "cardigan", "fake-name": "fashionable relaxed lively poised cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {
    "item-id": "2521310_8",
    "type": "cardigan",
    "fake-name": "contemporary quirky free-spirited refined cardigan",
    "image-path": "asset/clothes/cardigan/1.jpeg"
  },
  {"item-id": "2722297_4", "type": "cardigan", "fake-name": "sophisticated playful refined urbane cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2521310_4", "type": "cardigan", "fake-name": "classy vintage zen versatile cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310_4", "type": "cardigan", "fake-name": "classy vintage zen versatile cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2144424_8", "type": "cardigan", "fake-name": "glamorous minimalist urban bohemian cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2743996_14", "type": "cardigan", "fake-name": "sleek urban sleek sleek cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2071468_8", "type": "cardigan", "fake-name": "exquisite posh spontaneous trendsetting cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2766308_16", "type": "cardigan", "fake-name": "stylish cozy mellow contemporary cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2262637_14", "type": "cardigan", "fake-name": "sophisticated playful refined urbane cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2144424_14", "type": "cardigan", "fake-name": "elegant vibrant wholesome serene cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2094264_8", "type": "cardigan", "fake-name": "sleek urban sleek sleek cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310_4", "type": "cardigan", "fake-name": "classy vintage zen versatile cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2029039_8", "type": "cardigan", "fake-name": "sleek urban sleek sleek cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2743996_8", "type": "cardigan", "fake-name": "chic casual eclectic opulent cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2509818_20", "type": "cardigan", "fake-name": "striking dynamic sharp whimsical cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {
    "item-id": "2299144_4",
    "type": "cardigan",
    "fake-name": "contemporary quirky free-spirited refined cardigan",
    "image-path": "asset/clothes/cardigan/1.jpeg"
  },
  {"item-id": "2065252_4", "type": "cardigan", "fake-name": "stylish cozy mellow contemporary cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2766308_4", "type": "cardigan", "fake-name": "fashionable relaxed lively poised cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2261101_8", "type": "cardigan", "fake-name": "chic casual eclectic opulent cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {
    "item-id": "2521310_20",
    "type": "cardigan",
    "fake-name": "contemporary quirky free-spirited refined cardigan",
    "image-path": "asset/clothes/cardigan/1.jpeg"
  },
  {"item-id": "2029039_14", "type": "cardigan", "fake-name": "polished bohemian blissful organic cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2082039_8", "type": "cardigan", "fake-name": "sleek urban sleek sleek cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2743996_14", "type": "cardigan", "fake-name": "sleek urban sleek sleek cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2521310_4", "type": "cardigan", "fake-name": "classy vintage zen versatile cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2262637_20", "type": "cardigan", "fake-name": "chic casual eclectic opulent cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2144424_8", "type": "cardigan", "fake-name": "glamorous minimalist urban bohemian cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2743996_14", "type": "cardigan", "fake-name": "sleek urban sleek sleek cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2144424_14", "type": "cardigan", "fake-name": "elegant vibrant wholesome serene cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2299144_8", "type": "cardigan", "fake-name": "dapper eclectic graceful radiant cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310_4", "type": "cardigan", "fake-name": "classy vintage zen versatile cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2082039_20", "type": "cardigan", "fake-name": "stylish cozy mellow contemporary cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2509818_8", "type": "cardigan", "fake-name": "fashionable relaxed lively poised cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310_14", "type": "cardigan", "fake-name": "sleek urban sleek sleek cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2261101_8", "type": "cardigan", "fake-name": "chic casual eclectic opulent cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2621527_20", "type": "cardigan", "fake-name": "dapper eclectic graceful radiant cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2494511_14", "type": "cardigan", "fake-name": "glamorous minimalist urban bohemian cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2509818_8", "type": "cardigan", "fake-name": "fashionable relaxed lively poised cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310_14", "type": "cardigan", "fake-name": "sleek urban sleek sleek cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2743996_8", "type": "cardigan", "fake-name": "chic casual eclectic opulent cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2065252_8", "type": "cardigan", "fake-name": "stylish cozy mellow contemporary cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2127264_4", "type": "cardigan", "fake-name": "chic casual eclectic opulent cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {
    "item-id": "2521310_20",
    "type": "cardigan",
    "fake-name": "contemporary quirky free-spirited refined cardigan",
    "image-path": "asset/clothes/cardigan/1.jpeg"
  },
  {"item-id": "2509818_4", "type": "cardigan", "fake-name": "striking dynamic sharp whimsical cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2743996_14", "type": "cardigan", "fake-name": "sleek urban sleek sleek cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2299144_14", "type": "cardigan", "fake-name": "edgy radiant dynamic exuberant cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2262637_14", "type": "cardigan", "fake-name": "sophisticated playful refined urbane cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2555454_14", "type": "cardigan", "fake-name": "dapper eclectic graceful radiant cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2262637_14", "type": "cardigan", "fake-name": "sophisticated playful refined urbane cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2144424_8", "type": "cardigan", "fake-name": "glamorous minimalist urban bohemian cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {
    "item-id": "2127264_14",
    "type": "cardigan",
    "fake-name": "contemporary quirky free-spirited refined cardigan",
    "image-path": "asset/clothes/cardigan/3.jpeg"
  },
  {"item-id": "2538397_14", "type": "cardigan", "fake-name": "stylish cozy mellow contemporary cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2144424_4", "type": "cardigan", "fake-name": "dapper eclectic graceful radiant cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2262637_8", "type": "cardigan", "fake-name": "polished bohemian blissful organic cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2127264_20", "type": "cardigan", "fake-name": "chic casual eclectic opulent cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2029039_20", "type": "cardigan", "fake-name": "sophisticated playful refined urbane cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2144424_14", "type": "cardigan", "fake-name": "elegant vibrant wholesome serene cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2127264_4", "type": "cardigan", "fake-name": "chic casual eclectic opulent cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {
    "item-id": "2521310_8",
    "type": "cardigan",
    "fake-name": "contemporary quirky free-spirited refined cardigan",
    "image-path": "asset/clothes/cardigan/1.jpeg"
  },
  {"item-id": "2633784_4", "type": "cardigan", "fake-name": "chic casual eclectic opulent cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2127264_8", "type": "cardigan", "fake-name": "elegant vibrant wholesome serene cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310_14", "type": "cardigan", "fake-name": "sleek urban sleek sleek cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2509818_8", "type": "cardigan", "fake-name": "fashionable relaxed lively poised cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2615236_8", "type": "cardigan", "fake-name": "dapper eclectic graceful radiant cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2029039_14", "type": "cardigan", "fake-name": "polished bohemian blissful organic cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2555454_14", "type": "cardigan", "fake-name": "dapper eclectic graceful radiant cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2766308_12", "type": "cardigan", "fake-name": "trendy whimsical futuristic edgy cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2615236_8", "type": "cardigan", "fake-name": "dapper eclectic graceful radiant cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2144424_14", "type": "cardigan", "fake-name": "elegant vibrant wholesome serene cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2262637_20", "type": "cardigan", "fake-name": "chic casual eclectic opulent cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {
    "item-id": "2521310_8",
    "type": "cardigan",
    "fake-name": "contemporary quirky free-spirited refined cardigan",
    "image-path": "asset/clothes/cardigan/1.jpeg"
  },
  {
    "item-id": "2722297_8",
    "type": "cardigan",
    "fake-name": "contemporary quirky free-spirited refined cardigan",
    "image-path": "asset/clothes/cardigan/3.jpeg"
  },
  {"item-id": "2603249_8", "type": "cardigan", "fake-name": "sophisticated playful refined urbane cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2521310_4", "type": "cardigan", "fake-name": "classy vintage zen versatile cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2621527_14", "type": "cardigan", "fake-name": "sleek urban sleek sleek cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2521310_4", "type": "cardigan", "fake-name": "classy vintage zen versatile cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2299144_14", "type": "cardigan", "fake-name": "edgy radiant dynamic exuberant cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2144424_8", "type": "cardigan", "fake-name": "glamorous minimalist urban bohemian cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310_14", "type": "cardigan", "fake-name": "sleek urban sleek sleek cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {
    "item-id": "2521310_8",
    "type": "cardigan",
    "fake-name": "contemporary quirky free-spirited refined cardigan",
    "image-path": "asset/clothes/cardigan/1.jpeg"
  },
  {"item-id": "2743996_14", "type": "cardigan", "fake-name": "sleek urban sleek sleek cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2082039_4", "type": "cardigan", "fake-name": "stylish cozy mellow contemporary cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2633784_8", "type": "cardigan", "fake-name": "stylish cozy mellow contemporary cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2144424_14", "type": "cardigan", "fake-name": "elegant vibrant wholesome serene cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {
    "item-id": "2766308_20",
    "type": "cardigan",
    "fake-name": "contemporary quirky free-spirited refined cardigan",
    "image-path": "asset/clothes/cardigan/1.jpeg"
  },
  {"item-id": "2144424_14", "type": "cardigan", "fake-name": "elegant vibrant wholesome serene cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2521310_4", "type": "cardigan", "fake-name": "classy vintage zen versatile cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2603249_20", "type": "cardigan", "fake-name": "trendy whimsical futuristic edgy cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2127264_8", "type": "cardigan", "fake-name": "elegant vibrant wholesome serene cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2053422_14", "type": "cardigan", "fake-name": "polished bohemian blissful organic cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2144424_8", "type": "cardigan", "fake-name": "glamorous minimalist urban bohemian cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {
    "item-id": "2521310_8",
    "type": "cardigan",
    "fake-name": "contemporary quirky free-spirited refined cardigan",
    "image-path": "asset/clothes/cardigan/1.jpeg"
  },
  {"item-id": "2766308_4", "type": "cardigan", "fake-name": "fashionable relaxed lively poised cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2494511_20", "type": "cardigan", "fake-name": "glamorous minimalist urban bohemian cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310_4", "type": "cardigan", "fake-name": "classy vintage zen versatile cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2262637_8", "type": "cardigan", "fake-name": "polished bohemian blissful organic cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2615236_8", "type": "cardigan", "fake-name": "dapper eclectic graceful radiant cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2261101_4", "type": "cardigan", "fake-name": "trendy whimsical futuristic edgy cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {
    "item-id": "2521310_8",
    "type": "cardigan",
    "fake-name": "contemporary quirky free-spirited refined cardigan",
    "image-path": "asset/clothes/cardigan/1.jpeg"
  },
  {"item-id": "2621527_14", "type": "cardigan", "fake-name": "sleek urban sleek sleek cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2262637_14", "type": "cardigan", "fake-name": "sophisticated playful refined urbane cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {
    "item-id": "2521310_8",
    "type": "cardigan",
    "fake-name": "contemporary quirky free-spirited refined cardigan",
    "image-path": "asset/clothes/cardigan/1.jpeg"
  },
  {"item-id": "2509818_14", "type": "cardigan", "fake-name": "fashionable relaxed lively poised cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2262637_14", "type": "cardigan", "fake-name": "sophisticated playful refined urbane cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {
    "item-id": "2299144_4",
    "type": "cardigan",
    "fake-name": "contemporary quirky free-spirited refined cardigan",
    "image-path": "asset/clothes/cardigan/1.jpeg"
  },
  {"item-id": "2722297_14", "type": "cardigan", "fake-name": "glamorous minimalist urban bohemian cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2262637_14", "type": "cardigan", "fake-name": "sophisticated playful refined urbane cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2494511_14", "type": "cardigan", "fake-name": "glamorous minimalist urban bohemian cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2127264_20", "type": "cardigan", "fake-name": "chic casual eclectic opulent cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2743996_8", "type": "cardigan", "fake-name": "chic casual eclectic opulent cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2127264_4", "type": "cardigan", "fake-name": "chic casual eclectic opulent cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {
    "item-id": "2521310_8",
    "type": "cardigan",
    "fake-name": "contemporary quirky free-spirited refined cardigan",
    "image-path": "asset/clothes/cardigan/1.jpeg"
  },
  {"item-id": "2262637_14", "type": "cardigan", "fake-name": "sophisticated playful refined urbane cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2262637_4", "type": "cardigan", "fake-name": "glamorous minimalist urban bohemian cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {
    "item-id": "2521310_8",
    "type": "cardigan",
    "fake-name": "contemporary quirky free-spirited refined cardigan",
    "image-path": "asset/clothes/cardigan/1.jpeg"
  },
  {"item-id": "2082039_20", "type": "cardigan", "fake-name": "stylish cozy mellow contemporary cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2065252_20", "type": "cardigan", "fake-name": "chic casual eclectic opulent cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2262637_8", "type": "cardigan", "fake-name": "polished bohemian blissful organic cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2262637_14", "type": "cardigan", "fake-name": "sophisticated playful refined urbane cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2603249_20", "type": "cardigan", "fake-name": "trendy whimsical futuristic edgy cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2082039_20", "type": "cardigan", "fake-name": "stylish cozy mellow contemporary cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2538397_14", "type": "cardigan", "fake-name": "stylish cozy mellow contemporary cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2603249_8", "type": "cardigan", "fake-name": "sophisticated playful refined urbane cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2930997_14", "type": "cardigan", "fake-name": "dapper eclectic graceful radiant cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2029039_8", "type": "cardigan", "fake-name": "sleek urban sleek sleek cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2029039_4", "type": "cardigan", "fake-name": "dapper eclectic graceful radiant cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2743996_14", "type": "cardigan", "fake-name": "sleek urban sleek sleek cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2029039_4", "type": "cardigan", "fake-name": "dapper eclectic graceful radiant cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2611913_20", "type": "cardigan", "fake-name": "striking dynamic sharp whimsical cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2262637_8", "type": "cardigan", "fake-name": "polished bohemian blissful organic cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2521310_4", "type": "cardigan", "fake-name": "classy vintage zen versatile cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {
    "item-id": "2521310_20",
    "type": "cardigan",
    "fake-name": "contemporary quirky free-spirited refined cardigan",
    "image-path": "asset/clothes/cardigan/1.jpeg"
  },
  {"item-id": "2029039_4", "type": "cardigan", "fake-name": "dapper eclectic graceful radiant cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2521310_14", "type": "cardigan", "fake-name": "sleek urban sleek sleek cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2494511_14", "type": "cardigan", "fake-name": "glamorous minimalist urban bohemian cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2262637_14", "type": "cardigan", "fake-name": "sophisticated playful refined urbane cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {
    "item-id": "2299144_4",
    "type": "cardigan",
    "fake-name": "contemporary quirky free-spirited refined cardigan",
    "image-path": "asset/clothes/cardigan/1.jpeg"
  },
  {"item-id": "2509818_14", "type": "cardigan", "fake-name": "fashionable relaxed lively poised cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2521310_4", "type": "cardigan", "fake-name": "classy vintage zen versatile cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {
    "item-id": "2521310_8",
    "type": "cardigan",
    "fake-name": "contemporary quirky free-spirited refined cardigan",
    "image-path": "asset/clothes/cardigan/1.jpeg"
  },
  {"item-id": "2071468_20", "type": "cardigan", "fake-name": "edgy radiant dynamic exuberant cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2509818_20", "type": "cardigan", "fake-name": "striking dynamic sharp whimsical cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2029039_4", "type": "cardigan", "fake-name": "dapper eclectic graceful radiant cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2144424_14", "type": "cardigan", "fake-name": "elegant vibrant wholesome serene cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {
    "item-id": "2521310_8",
    "type": "cardigan",
    "fake-name": "contemporary quirky free-spirited refined cardigan",
    "image-path": "asset/clothes/cardigan/1.jpeg"
  },
  {"item-id": "2029039_8", "type": "cardigan", "fake-name": "sleek urban sleek sleek cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2127264_8", "type": "cardigan", "fake-name": "elegant vibrant wholesome serene cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2603249_8", "type": "cardigan", "fake-name": "sophisticated playful refined urbane cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2615236_20", "type": "cardigan", "fake-name": "striking dynamic sharp whimsical cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2743996_20", "type": "cardigan", "fake-name": "edgy radiant dynamic exuberant cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2509818_8", "type": "cardigan", "fake-name": "fashionable relaxed lively poised cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2262637_14", "type": "cardigan", "fake-name": "sophisticated playful refined urbane cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2029039_8", "type": "cardigan", "fake-name": "sleek urban sleek sleek cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2262637_14", "type": "cardigan", "fake-name": "sophisticated playful refined urbane cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2722297_14", "type": "cardigan", "fake-name": "glamorous minimalist urban bohemian cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2951824_14", "type": "cardigan", "fake-name": "fashionable relaxed lively poised cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2509818_20", "type": "cardigan", "fake-name": "striking dynamic sharp whimsical cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2094264_8", "type": "cardigan", "fake-name": "sleek urban sleek sleek cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {
    "item-id": "2521310_8",
    "type": "cardigan",
    "fake-name": "contemporary quirky free-spirited refined cardigan",
    "image-path": "asset/clothes/cardigan/1.jpeg"
  },
  {"item-id": "2262637_4", "type": "cardigan", "fake-name": "glamorous minimalist urban bohemian cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2144424_8", "type": "cardigan", "fake-name": "glamorous minimalist urban bohemian cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310_14", "type": "cardigan", "fake-name": "sleek urban sleek sleek cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2262637_20", "type": "cardigan", "fake-name": "chic casual eclectic opulent cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2262637_20", "type": "cardigan", "fake-name": "chic casual eclectic opulent cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2029039_14", "type": "cardigan", "fake-name": "polished bohemian blissful organic cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2299144_20", "type": "cardigan", "fake-name": "dapper eclectic graceful radiant cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2633784_4", "type": "cardigan", "fake-name": "chic casual eclectic opulent cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2494511_8", "type": "cardigan", "fake-name": "posh ethereal regal ethereal cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2603249_4", "type": "cardigan", "fake-name": "fashionable relaxed lively poised cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2127264_20", "type": "cardigan", "fake-name": "chic casual eclectic opulent cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2262637_14", "type": "cardigan", "fake-name": "sophisticated playful refined urbane cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2299144_14", "type": "cardigan", "fake-name": "edgy radiant dynamic exuberant cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2127264_4", "type": "cardigan", "fake-name": "chic casual eclectic opulent cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2538397_4", "type": "cardigan", "fake-name": "elegant vibrant wholesome serene cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2144424_14", "type": "cardigan", "fake-name": "elegant vibrant wholesome serene cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2743996_14", "type": "cardigan", "fake-name": "sleek urban sleek sleek cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2029039_14", "type": "cardigan", "fake-name": "polished bohemian blissful organic cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2127264_4", "type": "cardigan", "fake-name": "chic casual eclectic opulent cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {
    "item-id": "2521310_20",
    "type": "cardigan",
    "fake-name": "contemporary quirky free-spirited refined cardigan",
    "image-path": "asset/clothes/cardigan/1.jpeg"
  },
  {"item-id": "2144424_14", "type": "cardigan", "fake-name": "elegant vibrant wholesome serene cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2633784_4", "type": "cardigan", "fake-name": "chic casual eclectic opulent cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2611913_8", "type": "cardigan", "fake-name": "stylish cozy mellow contemporary cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {
    "item-id": "2521310_20",
    "type": "cardigan",
    "fake-name": "contemporary quirky free-spirited refined cardigan",
    "image-path": "asset/clothes/cardigan/1.jpeg"
  },
  {"item-id": "2262637_14", "type": "cardigan", "fake-name": "sophisticated playful refined urbane cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2262637_14", "type": "cardigan", "fake-name": "sophisticated playful refined urbane cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2743996_8", "type": "cardigan", "fake-name": "chic casual eclectic opulent cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2065252_4", "type": "cardigan", "fake-name": "stylish cozy mellow contemporary cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2262637_4", "type": "cardigan", "fake-name": "glamorous minimalist urban bohemian cardigan", "image-path": "asset/clothes/cardigan/3.jpeg"},
  {"item-id": "2509818_20", "type": "cardigan", "fake-name": "striking dynamic sharp whimsical cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2521310_4", "type": "cardigan", "fake-name": "classy vintage zen versatile cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2127264_8", "type": "cardigan", "fake-name": "elegant vibrant wholesome serene cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"},
  {"item-id": "2555454_8", "type": "cardigan", "fake-name": "glamorous minimalist urban bohemian cardigan", "image-path": "asset/clothes/cardigan/1.jpeg"}
];
