final culotte_list = [
  {"item-id": "2668203", "type": "culotte", "fake-name": "elegant radiant magnetic ethereal culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "glamorous radiant regal effortless culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "radiant relaxed eclectic exuberant culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2762448", "type": "culotte", "fake-name": "fashionable urban mellow whimsical culotte", "image-path": "asset/clothes/culotte/1.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "elegant cozy sleek trendsetting culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "trendy radiant zen edgy culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "radiant dynamic spontaneous exuberant culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "chic quirky lively bohemian culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "striking vibrant graceful contemporary culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "striking playful free-spirited radiant culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "stylish minimalist blissful urbane culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "striking ethereal sharp effortless culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "sophisticated radiant zen whimsical culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "contemporary casual refined exuberant culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "radiant playful lively poised culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "striking ethereal refined urbane culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "glamorous vintage graceful radiant culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "radiant relaxed dynamic opulent culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "trendy relaxed wholesome effortless culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "chic minimalist mellow urbane culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "fashionable cozy regal edgy culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "fashionable casual refined ethereal culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "sleek playful zen organic culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "dapper bohemian lively exuberant culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "contemporary dynamic spontaneous effortless culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "glamorous casual lively sleek culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "sophisticated playful mellow whimsical culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "classy playful eclectic contemporary culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "fashionable vintage lively opulent culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "exquisite urban spontaneous poised culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2762448", "type": "culotte", "fake-name": "fashionable quirky free-spirited whimsical culotte", "image-path": "asset/clothes/culotte/1.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "sleek playful eclectic exuberant culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "chic dynamic eclectic exuberant culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "fashionable eclectic mellow refined culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "dapper casual graceful ethereal culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {
    "item-id": "2902058",
    "type": "culotte",
    "fake-name": "contemporary bohemian free-spirited effortless culotte",
    "image-path": "asset/clothes/culotte/3.jpeg"
  },
  {"item-id": "2668203", "type": "culotte", "fake-name": "contemporary radiant graceful exuberant culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "radiant posh eclectic edgy culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "posh minimalist refined refined culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "sophisticated bohemian lively contemporary culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "fashionable relaxed regal suave culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2762448", "type": "culotte", "fake-name": "polished bohemian magnetic versatile culotte", "image-path": "asset/clothes/culotte/1.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "edgy vintage eclectic contemporary culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "stylish relaxed graceful poised culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "edgy eclectic spontaneous radiant culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "chic ethereal zen versatile culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "contemporary urban sleek opulent culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "classy vibrant zen effortless culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "polished urban urban refined culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "exquisite urban magnetic urbane culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "exquisite bohemian refined opulent culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2762448", "type": "culotte", "fake-name": "contemporary dynamic eclectic versatile culotte", "image-path": "asset/clothes/culotte/1.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "dapper urban futuristic effortless culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "contemporary casual lively edgy culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "exquisite radiant graceful edgy culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "chic whimsical blissful opulent culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "exquisite eclectic ethereal sleek culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "dapper minimalist graceful opulent culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2762448", "type": "culotte", "fake-name": "trendy quirky futuristic contemporary culotte", "image-path": "asset/clothes/culotte/1.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "alluring quirky wholesome refined culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "radiant relaxed dynamic edgy culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "exquisite vibrant blissful versatile culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "exquisite vintage graceful serene culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "trendy radiant sharp opulent culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "sleek relaxed refined opulent culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "polished dynamic free-spirited poised culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "contemporary cozy spontaneous exuberant culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "classy playful sleek radiant culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "alluring eclectic ethereal bohemian culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "polished urban regal radiant culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "exquisite cozy wholesome edgy culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "edgy vintage spontaneous urbane culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2668203", "type": "culotte", "fake-name": "sleek ethereal sharp poised culotte", "image-path": "asset/clothes/culotte/4.jpeg"},
  {"item-id": "2902058", "type": "culotte", "fake-name": "fashionable relaxed eclectic opulent culotte", "image-path": "asset/clothes/culotte/3.jpeg"},
  {"item-id": "2762448", "type": "culotte", "fake-name": "exquisite quirky ethereal effortless culotte", "image-path": "asset/clothes/culotte/1.jpeg"}
];
