final kimono_list = [
  {"item-id": "2412589_4", "type": "kimono", "fake-name": "sleek urban sleek sleek kimono", "image-path": "asset/clothes/kimono/3.jpeg"},
  {"item-id": "2412589_20", "type": "kimono", "fake-name": "dapper eclectic graceful radiant kimono", "image-path": "asset/clothes/kimono/1.jpeg"},
  {"item-id": "2412589_8", "type": "kimono", "fake-name": "contemporary quirky free-spirited refined kimono", "image-path": "asset/clothes/kimono/3.jpeg"},
  {"item-id": "2412589_14", "type": "kimono", "fake-name": "sleek urban sleek sleek kimono", "image-path": "asset/clothes/kimono/3.jpeg"},
  {"item-id": "2412589_8", "type": "kimono", "fake-name": "contemporary quirky free-spirited refined kimono", "image-path": "asset/clothes/kimono/3.jpeg"},
  {"item-id": "2412589_14", "type": "kimono", "fake-name": "sleek urban sleek sleek kimono", "image-path": "asset/clothes/kimono/3.jpeg"},
  {"item-id": "2412589_8", "type": "kimono", "fake-name": "contemporary quirky free-spirited refined kimono", "image-path": "asset/clothes/kimono/3.jpeg"},
  {"item-id": "2412589_4", "type": "kimono", "fake-name": "sleek urban sleek sleek kimono", "image-path": "asset/clothes/kimono/3.jpeg"},
  {"item-id": "2412589_14", "type": "kimono", "fake-name": "sleek urban sleek sleek kimono", "image-path": "asset/clothes/kimono/3.jpeg"},
  {"item-id": "2412589_8", "type": "kimono", "fake-name": "contemporary quirky free-spirited refined kimono", "image-path": "asset/clothes/kimono/3.jpeg"},
  {"item-id": "2691465_4", "type": "kimono", "fake-name": "sleek urban sleek sleek kimono", "image-path": "asset/clothes/kimono/3.jpeg"},
  {"item-id": "2412589_14", "type": "kimono", "fake-name": "sleek urban sleek sleek kimono", "image-path": "asset/clothes/kimono/3.jpeg"},
  {"item-id": "2412589_8", "type": "kimono", "fake-name": "contemporary quirky free-spirited refined kimono", "image-path": "asset/clothes/kimono/3.jpeg"},
  {"item-id": "2412589_4", "type": "kimono", "fake-name": "sleek urban sleek sleek kimono", "image-path": "asset/clothes/kimono/3.jpeg"},
  {"item-id": "2412589_20", "type": "kimono", "fake-name": "dapper eclectic graceful radiant kimono", "image-path": "asset/clothes/kimono/1.jpeg"},
  {"item-id": "2412589_14", "type": "kimono", "fake-name": "sleek urban sleek sleek kimono", "image-path": "asset/clothes/kimono/3.jpeg"},
  {"item-id": "2412589_4", "type": "kimono", "fake-name": "sleek urban sleek sleek kimono", "image-path": "asset/clothes/kimono/3.jpeg"},
  {"item-id": "2412589_8", "type": "kimono", "fake-name": "contemporary quirky free-spirited refined kimono", "image-path": "asset/clothes/kimono/3.jpeg"},
  {"item-id": "2412589_20", "type": "kimono", "fake-name": "dapper eclectic graceful radiant kimono", "image-path": "asset/clothes/kimono/1.jpeg"},
  {"item-id": "2412589_4", "type": "kimono", "fake-name": "sleek urban sleek sleek kimono", "image-path": "asset/clothes/kimono/3.jpeg"},
  {"item-id": "2412589_8", "type": "kimono", "fake-name": "contemporary quirky free-spirited refined kimono", "image-path": "asset/clothes/kimono/3.jpeg"},
  {"item-id": "2412589_8", "type": "kimono", "fake-name": "contemporary quirky free-spirited refined kimono", "image-path": "asset/clothes/kimono/3.jpeg"},
  {"item-id": "2412589_8", "type": "kimono", "fake-name": "contemporary quirky free-spirited refined kimono", "image-path": "asset/clothes/kimono/3.jpeg"},
  {"item-id": "2412589_4", "type": "kimono", "fake-name": "sleek urban sleek sleek kimono", "image-path": "asset/clothes/kimono/3.jpeg"}
];
