final leggings_list = [
  {"item-id": "2595752", "type": "leggings", "fake-name": "polished bohemian sleek radiant leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "chic quirky sleek poised leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2794512", "type": "leggings", "fake-name": "dapper vibrant futuristic sleek leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2900682", "type": "leggings", "fake-name": "sleek radiant spontaneous urbane leggings", "image-path": "asset/clothes/leggings/3.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "sleek vibrant futuristic exuberant leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "dapper cozy spontaneous contemporary leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2794512", "type": "leggings", "fake-name": "trendy quirky graceful contemporary leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2794512", "type": "leggings", "fake-name": "sophisticated eclectic lively bohemian leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2794512", "type": "leggings", "fake-name": "sophisticated minimalist refined urbane leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2125981", "type": "leggings", "fake-name": "sleek casual blissful bohemian leggings", "image-path": "asset/clothes/leggings/2.jpeg"},
  {"item-id": "2794512", "type": "leggings", "fake-name": "fashionable posh blissful bohemian leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2125981", "type": "leggings", "fake-name": "sleek playful spontaneous suave leggings", "image-path": "asset/clothes/leggings/2.jpeg"},
  {"item-id": "2794512", "type": "leggings", "fake-name": "alluring cozy free-spirited suave leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "dapper posh futuristic ethereal leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2659134", "type": "leggings", "fake-name": "exquisite eclectic eclectic effortless leggings", "image-path": "asset/clothes/leggings/3.jpeg"},
  {"item-id": "2794512", "type": "leggings", "fake-name": "dapper vintage graceful edgy leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "trendy playful regal contemporary leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2184285", "type": "leggings", "fake-name": "sophisticated bohemian blissful radiant leggings", "image-path": "asset/clothes/leggings/2.jpeg"},
  {"item-id": "2794512", "type": "leggings", "fake-name": "chic cozy graceful ethereal leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "radiant ethereal eclectic suave leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2184285", "type": "leggings", "fake-name": "contemporary bohemian wholesome edgy leggings", "image-path": "asset/clothes/leggings/2.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "edgy relaxed graceful urbane leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "posh quirky magnetic urbane leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2794512", "type": "leggings", "fake-name": "trendy whimsical refined edgy leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "exquisite urban ethereal ethereal leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "classy posh sharp edgy leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2184285", "type": "leggings", "fake-name": "fashionable urban zen exuberant leggings", "image-path": "asset/clothes/leggings/2.jpeg"},
  {"item-id": "2659134", "type": "leggings", "fake-name": "posh bohemian blissful bohemian leggings", "image-path": "asset/clothes/leggings/3.jpeg"},
  {"item-id": "2794512", "type": "leggings", "fake-name": "trendy ethereal sharp organic leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2794512", "type": "leggings", "fake-name": "polished casual sharp effortless leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "posh relaxed urban bohemian leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "glamorous radiant sleek urbane leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "polished cozy magnetic suave leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2697691", "type": "leggings", "fake-name": "dapper eclectic eclectic serene leggings", "image-path": "asset/clothes/leggings/4.jpeg"},
  {"item-id": "2125981", "type": "leggings", "fake-name": "glamorous eclectic refined exuberant leggings", "image-path": "asset/clothes/leggings/2.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "chic radiant free-spirited urbane leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "glamorous vibrant urban trendsetting leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2794512", "type": "leggings", "fake-name": "exquisite whimsical lively poised leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "fashionable bohemian spontaneous sleek leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2794512", "type": "leggings", "fake-name": "posh minimalist spontaneous radiant leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {
    "item-id": "2595752",
    "type": "leggings",
    "fake-name": "sophisticated ethereal ethereal trendsetting leggings",
    "image-path": "asset/clothes/leggings/1.jpeg"
  },
  {"item-id": "2595752", "type": "leggings", "fake-name": "striking casual zen edgy leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2900682", "type": "leggings", "fake-name": "edgy radiant wholesome exuberant leggings", "image-path": "asset/clothes/leggings/3.jpeg"},
  {"item-id": "2900682", "type": "leggings", "fake-name": "exquisite cozy spontaneous poised leggings", "image-path": "asset/clothes/leggings/3.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "glamorous dynamic mellow opulent leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "polished dynamic mellow urbane leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2794512", "type": "leggings", "fake-name": "contemporary eclectic free-spirited poised leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "classy vibrant dynamic versatile leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2794512", "type": "leggings", "fake-name": "fashionable relaxed ethereal exuberant leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "sleek playful ethereal ethereal leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2697691", "type": "leggings", "fake-name": "sophisticated bohemian refined edgy leggings", "image-path": "asset/clothes/leggings/4.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "elegant urban blissful organic leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2794512", "type": "leggings", "fake-name": "contemporary quirky magnetic whimsical leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "stylish vintage lively urbane leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "contemporary vintage lively bohemian leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "sophisticated whimsical dynamic effortless leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2697691", "type": "leggings", "fake-name": "alluring minimalist wholesome urbane leggings", "image-path": "asset/clothes/leggings/4.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "exquisite posh sleek sleek leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "contemporary whimsical sleek exuberant leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "chic eclectic urban refined leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "fashionable relaxed regal sleek leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "edgy posh magnetic whimsical leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "elegant eclectic urban whimsical leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2659134", "type": "leggings", "fake-name": "posh radiant futuristic urbane leggings", "image-path": "asset/clothes/leggings/3.jpeg"},
  {"item-id": "2794512", "type": "leggings", "fake-name": "fashionable playful refined suave leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2794512", "type": "leggings", "fake-name": "posh vibrant lively refined leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2900682", "type": "leggings", "fake-name": "polished minimalist zen serene leggings", "image-path": "asset/clothes/leggings/3.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "striking posh magnetic trendsetting leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "fashionable radiant mellow suave leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2900682", "type": "leggings", "fake-name": "trendy minimalist mellow urbane leggings", "image-path": "asset/clothes/leggings/3.jpeg"},
  {"item-id": "2900682", "type": "leggings", "fake-name": "polished relaxed sleek versatile leggings", "image-path": "asset/clothes/leggings/3.jpeg"},
  {"item-id": "2659134", "type": "leggings", "fake-name": "chic radiant spontaneous bohemian leggings", "image-path": "asset/clothes/leggings/3.jpeg"},
  {"item-id": "2184285", "type": "leggings", "fake-name": "posh cozy futuristic whimsical leggings", "image-path": "asset/clothes/leggings/2.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "glamorous relaxed sharp edgy leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2900682", "type": "leggings", "fake-name": "radiant relaxed sleek whimsical leggings", "image-path": "asset/clothes/leggings/3.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "edgy whimsical blissful serene leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2794512", "type": "leggings", "fake-name": "glamorous ethereal regal organic leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "striking eclectic urban radiant leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2659134", "type": "leggings", "fake-name": "edgy ethereal eclectic ethereal leggings", "image-path": "asset/clothes/leggings/3.jpeg"},
  {"item-id": "2794512", "type": "leggings", "fake-name": "fashionable minimalist ethereal refined leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "fashionable radiant regal urbane leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "radiant relaxed mellow edgy leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2794512", "type": "leggings", "fake-name": "contemporary eclectic free-spirited sleek leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2794512", "type": "leggings", "fake-name": "contemporary whimsical urban whimsical leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2659134", "type": "leggings", "fake-name": "fashionable ethereal sharp trendsetting leggings", "image-path": "asset/clothes/leggings/3.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "sleek minimalist graceful effortless leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2900682", "type": "leggings", "fake-name": "stylish vintage regal trendsetting leggings", "image-path": "asset/clothes/leggings/3.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "chic dynamic refined sleek leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {
    "item-id": "2595752",
    "type": "leggings",
    "fake-name": "contemporary casual free-spirited exuberant leggings",
    "image-path": "asset/clothes/leggings/1.jpeg"
  },
  {"item-id": "2595752", "type": "leggings", "fake-name": "trendy posh regal contemporary leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2659134", "type": "leggings", "fake-name": "polished ethereal sleek effortless leggings", "image-path": "asset/clothes/leggings/3.jpeg"},
  {"item-id": "2659134", "type": "leggings", "fake-name": "trendy vibrant graceful organic leggings", "image-path": "asset/clothes/leggings/3.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "classy casual refined refined leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2697691", "type": "leggings", "fake-name": "alluring ethereal wholesome suave leggings", "image-path": "asset/clothes/leggings/4.jpeg"},
  {"item-id": "2794512", "type": "leggings", "fake-name": "stylish vintage futuristic effortless leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2659134", "type": "leggings", "fake-name": "posh eclectic ethereal opulent leggings", "image-path": "asset/clothes/leggings/3.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "fashionable quirky wholesome suave leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2794512", "type": "leggings", "fake-name": "trendy whimsical refined sleek leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "alluring vintage futuristic effortless leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2541502", "type": "leggings", "fake-name": "radiant quirky lively edgy leggings", "image-path": "asset/clothes/leggings/3.jpeg"},
  {"item-id": "2184285", "type": "leggings", "fake-name": "classy quirky wholesome contemporary leggings", "image-path": "asset/clothes/leggings/2.jpeg"},
  {"item-id": "2900682", "type": "leggings", "fake-name": "elegant bohemian mellow exuberant leggings", "image-path": "asset/clothes/leggings/3.jpeg"},
  {"item-id": "2900682", "type": "leggings", "fake-name": "polished playful ethereal sleek leggings", "image-path": "asset/clothes/leggings/3.jpeg"},
  {"item-id": "2125981", "type": "leggings", "fake-name": "radiant vibrant sleek effortless leggings", "image-path": "asset/clothes/leggings/2.jpeg"},
  {"item-id": "2900682", "type": "leggings", "fake-name": "contemporary radiant mellow opulent leggings", "image-path": "asset/clothes/leggings/3.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "exquisite radiant regal refined leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "dapper eclectic blissful suave leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2125981", "type": "leggings", "fake-name": "contemporary whimsical spontaneous urbane leggings", "image-path": "asset/clothes/leggings/2.jpeg"},
  {"item-id": "2794512", "type": "leggings", "fake-name": "glamorous relaxed sleek organic leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "trendy posh free-spirited trendsetting leggings", "image-path": "asset/clothes/leggings/1.jpeg"},
  {"item-id": "2125981", "type": "leggings", "fake-name": "posh whimsical ethereal poised leggings", "image-path": "asset/clothes/leggings/2.jpeg"},
  {"item-id": "2595752", "type": "leggings", "fake-name": "polished playful zen suave leggings", "image-path": "asset/clothes/leggings/1.jpeg"}
];
