final pullover_list = [
  {"item-id": "2349556_14", "type": "pullover", "fake-name": "classy vintage zen versatile pullover", "image-path": "asset/clothes/pullover/3.jpeg"},
  {"item-id": "2130194_8", "type": "pullover", "fake-name": "dapper eclectic graceful radiant pullover", "image-path": "asset/clothes/pullover/1.jpeg"},
  {"item-id": "2610728_14", "type": "pullover", "fake-name": "polished bohemian blissful organic pullover", "image-path": "asset/clothes/pullover/3.jpeg"},
  {"item-id": "2130194_14", "type": "pullover", "fake-name": "sophisticated playful refined urbane pullover", "image-path": "asset/clothes/pullover/3.jpeg"},
  {
    "item-id": "2349556_20",
    "type": "pullover",
    "fake-name": "contemporary quirky free-spirited refined pullover",
    "image-path": "asset/clothes/pullover/1.jpeg"
  },
  {"item-id": "2130194_14", "type": "pullover", "fake-name": "sophisticated playful refined urbane pullover", "image-path": "asset/clothes/pullover/3.jpeg"},
  {
    "item-id": "2349556_20",
    "type": "pullover",
    "fake-name": "contemporary quirky free-spirited refined pullover",
    "image-path": "asset/clothes/pullover/1.jpeg"
  },
  {"item-id": "2349556_8", "type": "pullover", "fake-name": "classy vintage zen versatile pullover", "image-path": "asset/clothes/pullover/1.jpeg"},
  {"item-id": "2130194_20", "type": "pullover", "fake-name": "exquisite posh spontaneous trendsetting pullover", "image-path": "asset/clothes/pullover/1.jpeg"},
  {"item-id": "2203965_4", "type": "pullover", "fake-name": "polished bohemian blissful organic pullover", "image-path": "asset/clothes/pullover/3.jpeg"},
  {"item-id": "2349556_26", "type": "pullover", "fake-name": "posh ethereal regal ethereal pullover", "image-path": "asset/clothes/pullover/3.jpeg"},
  {"item-id": "2130194_20", "type": "pullover", "fake-name": "exquisite posh spontaneous trendsetting pullover", "image-path": "asset/clothes/pullover/1.jpeg"},
  {"item-id": "2113495_4", "type": "pullover", "fake-name": "dapper eclectic graceful radiant pullover", "image-path": "asset/clothes/pullover/3.jpeg"},
  {"item-id": "2555342_20", "type": "pullover", "fake-name": "striking dynamic sharp whimsical pullover", "image-path": "asset/clothes/pullover/1.jpeg"},
  {"item-id": "2130194_14", "type": "pullover", "fake-name": "sophisticated playful refined urbane pullover", "image-path": "asset/clothes/pullover/3.jpeg"},
  {"item-id": "2349556_4", "type": "pullover", "fake-name": "trendy whimsical futuristic edgy pullover", "image-path": "asset/clothes/pullover/1.jpeg"},
  {"item-id": "2708138_14", "type": "pullover", "fake-name": "dapper eclectic graceful radiant pullover", "image-path": "asset/clothes/pullover/3.jpeg"},
  {"item-id": "2610728_14", "type": "pullover", "fake-name": "polished bohemian blissful organic pullover", "image-path": "asset/clothes/pullover/3.jpeg"},
  {"item-id": "2130194_20", "type": "pullover", "fake-name": "exquisite posh spontaneous trendsetting pullover", "image-path": "asset/clothes/pullover/1.jpeg"},
  {
    "item-id": "2555342_8",
    "type": "pullover",
    "fake-name": "contemporary quirky free-spirited refined pullover",
    "image-path": "asset/clothes/pullover/1.jpeg"
  },
  {"item-id": "2349556_14", "type": "pullover", "fake-name": "classy vintage zen versatile pullover", "image-path": "asset/clothes/pullover/3.jpeg"},
  {"item-id": "2130194_20", "type": "pullover", "fake-name": "exquisite posh spontaneous trendsetting pullover", "image-path": "asset/clothes/pullover/1.jpeg"},
  {"item-id": "2689743_8", "type": "pullover", "fake-name": "fashionable relaxed lively poised pullover", "image-path": "asset/clothes/pullover/3.jpeg"},
  {"item-id": "2130194_4", "type": "pullover", "fake-name": "edgy radiant dynamic exuberant pullover", "image-path": "asset/clothes/pullover/1.jpeg"},
  {"item-id": "2130194_20", "type": "pullover", "fake-name": "exquisite posh spontaneous trendsetting pullover", "image-path": "asset/clothes/pullover/1.jpeg"},
  {"item-id": "2689743_20", "type": "pullover", "fake-name": "stylish cozy mellow contemporary pullover", "image-path": "asset/clothes/pullover/1.jpeg"},
  {"item-id": "2130194_20", "type": "pullover", "fake-name": "exquisite posh spontaneous trendsetting pullover", "image-path": "asset/clothes/pullover/1.jpeg"},
  {"item-id": "2113495_20", "type": "pullover", "fake-name": "dapper eclectic graceful radiant pullover", "image-path": "asset/clothes/pullover/1.jpeg"},
  {"item-id": "2075370_14", "type": "pullover", "fake-name": "edgy radiant dynamic exuberant pullover", "image-path": "asset/clothes/pullover/3.jpeg"},
  {"item-id": "2349556_26", "type": "pullover", "fake-name": "posh ethereal regal ethereal pullover", "image-path": "asset/clothes/pullover/3.jpeg"},
  {
    "item-id": "2349556_20",
    "type": "pullover",
    "fake-name": "contemporary quirky free-spirited refined pullover",
    "image-path": "asset/clothes/pullover/1.jpeg"
  },
  {"item-id": "2708138_20", "type": "pullover", "fake-name": "elegant vibrant wholesome serene pullover", "image-path": "asset/clothes/pullover/1.jpeg"},
  {"item-id": "2610728_14", "type": "pullover", "fake-name": "polished bohemian blissful organic pullover", "image-path": "asset/clothes/pullover/3.jpeg"},
  {"item-id": "2113495_4", "type": "pullover", "fake-name": "dapper eclectic graceful radiant pullover", "image-path": "asset/clothes/pullover/3.jpeg"},
  {"item-id": "2075370_8", "type": "pullover", "fake-name": "elegant vibrant wholesome serene pullover", "image-path": "asset/clothes/pullover/1.jpeg"},
  {"item-id": "2349556_8", "type": "pullover", "fake-name": "classy vintage zen versatile pullover", "image-path": "asset/clothes/pullover/1.jpeg"},
  {"item-id": "2130194_8", "type": "pullover", "fake-name": "dapper eclectic graceful radiant pullover", "image-path": "asset/clothes/pullover/1.jpeg"},
  {"item-id": "2130194_8", "type": "pullover", "fake-name": "dapper eclectic graceful radiant pullover", "image-path": "asset/clothes/pullover/1.jpeg"},
  {"item-id": "2130194_8", "type": "pullover", "fake-name": "dapper eclectic graceful radiant pullover", "image-path": "asset/clothes/pullover/1.jpeg"},
  {"item-id": "2610728_14", "type": "pullover", "fake-name": "polished bohemian blissful organic pullover", "image-path": "asset/clothes/pullover/3.jpeg"},
  {"item-id": "2075370_8", "type": "pullover", "fake-name": "elegant vibrant wholesome serene pullover", "image-path": "asset/clothes/pullover/1.jpeg"},
  {"item-id": "2610728_20", "type": "pullover", "fake-name": "exquisite posh spontaneous trendsetting pullover", "image-path": "asset/clothes/pullover/1.jpeg"},
  {"item-id": "2349556_4", "type": "pullover", "fake-name": "trendy whimsical futuristic edgy pullover", "image-path": "asset/clothes/pullover/1.jpeg"},
  {"item-id": "2130194_20", "type": "pullover", "fake-name": "exquisite posh spontaneous trendsetting pullover", "image-path": "asset/clothes/pullover/1.jpeg"},
  {"item-id": "2610728_14", "type": "pullover", "fake-name": "polished bohemian blissful organic pullover", "image-path": "asset/clothes/pullover/3.jpeg"}
];
