final sweatshirt_list = [
  {"item-id": "2110905", "type": "sweatshirt", "fake-name": "exquisite casual regal radiant sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {
    "item-id": "2842622",
    "type": "sweatshirt",
    "fake-name": "contemporary bohemian eclectic refined sweatshirt",
    "image-path": "asset/clothes/sweatshirt/3.jpeg"
  },
  {
    "item-id": "2616173",
    "type": "sweatshirt",
    "fake-name": "dapper eclectic free-spirited contemporary sweatshirt",
    "image-path": "asset/clothes/sweatshirt/2.jpeg"
  },
  {
    "item-id": "2120713",
    "type": "sweatshirt",
    "fake-name": "glamorous whimsical graceful ethereal sweatshirt",
    "image-path": "asset/clothes/sweatshirt/2.jpeg"
  },
  {"item-id": "2183771", "type": "sweatshirt", "fake-name": "radiant relaxed sharp edgy sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {
    "item-id": "2407112",
    "type": "sweatshirt",
    "fake-name": "alluring dynamic free-spirited whimsical sweatshirt",
    "image-path": "asset/clothes/sweatshirt/1.jpeg"
  },
  {"item-id": "2165820", "type": "sweatshirt", "fake-name": "sleek cozy ethereal poised sweatshirt", "image-path": "asset/clothes/sweatshirt/1.jpeg"},
  {"item-id": "2165820", "type": "sweatshirt", "fake-name": "dapper dynamic free-spirited suave sweatshirt", "image-path": "asset/clothes/sweatshirt/1.jpeg"},
  {"item-id": "2185289", "type": "sweatshirt", "fake-name": "chic vibrant blissful trendsetting sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {
    "item-id": "2034791",
    "type": "sweatshirt",
    "fake-name": "sophisticated urban futuristic opulent sweatshirt",
    "image-path": "asset/clothes/sweatshirt/4.jpeg"
  },
  {
    "item-id": "2185289",
    "type": "sweatshirt",
    "fake-name": "contemporary radiant dynamic contemporary sweatshirt",
    "image-path": "asset/clothes/sweatshirt/2.jpeg"
  },
  {"item-id": "2709694", "type": "sweatshirt", "fake-name": "radiant ethereal dynamic urbane sweatshirt", "image-path": "asset/clothes/sweatshirt/3.jpeg"},
  {
    "item-id": "2239187",
    "type": "sweatshirt",
    "fake-name": "elegant relaxed wholesome contemporary sweatshirt",
    "image-path": "asset/clothes/sweatshirt/4.jpeg"
  },
  {"item-id": "2034791", "type": "sweatshirt", "fake-name": "dapper bohemian lively suave sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2407112", "type": "sweatshirt", "fake-name": "chic eclectic refined sleek sweatshirt", "image-path": "asset/clothes/sweatshirt/1.jpeg"},
  {
    "item-id": "2239187",
    "type": "sweatshirt",
    "fake-name": "alluring radiant futuristic contemporary sweatshirt",
    "image-path": "asset/clothes/sweatshirt/4.jpeg"
  },
  {
    "item-id": "2183771",
    "type": "sweatshirt",
    "fake-name": "fashionable playful magnetic versatile sweatshirt",
    "image-path": "asset/clothes/sweatshirt/4.jpeg"
  },
  {"item-id": "2185289", "type": "sweatshirt", "fake-name": "exquisite cozy graceful poised sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2193444", "type": "sweatshirt", "fake-name": "striking cozy mellow sleek sweatshirt", "image-path": "asset/clothes/sweatshirt/1.jpeg"},
  {"item-id": "2239187", "type": "sweatshirt", "fake-name": "classy cozy wholesome contemporary sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2034791", "type": "sweatshirt", "fake-name": "dapper minimalist blissful poised sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2587162", "type": "sweatshirt", "fake-name": "glamorous minimalist sleek opulent sweatshirt", "image-path": "asset/clothes/sweatshirt/3.jpeg"},
  {"item-id": "2912925", "type": "sweatshirt", "fake-name": "chic urban blissful versatile sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2120713", "type": "sweatshirt", "fake-name": "stylish vintage eclectic bohemian sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2759778", "type": "sweatshirt", "fake-name": "stylish posh blissful trendsetting sweatshirt", "image-path": "asset/clothes/sweatshirt/3.jpeg"},
  {"item-id": "2709694", "type": "sweatshirt", "fake-name": "sleek cozy urban suave sweatshirt", "image-path": "asset/clothes/sweatshirt/3.jpeg"},
  {"item-id": "2193444", "type": "sweatshirt", "fake-name": "striking minimalist sleek exuberant sweatshirt", "image-path": "asset/clothes/sweatshirt/1.jpeg"},
  {"item-id": "2033787", "type": "sweatshirt", "fake-name": "striking minimalist zen radiant sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2407112", "type": "sweatshirt", "fake-name": "classy relaxed blissful opulent sweatshirt", "image-path": "asset/clothes/sweatshirt/1.jpeg"},
  {"item-id": "2254449", "type": "sweatshirt", "fake-name": "contemporary playful lively opulent sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2407112", "type": "sweatshirt", "fake-name": "elegant quirky sharp bohemian sweatshirt", "image-path": "asset/clothes/sweatshirt/1.jpeg"},
  {"item-id": "2185289", "type": "sweatshirt", "fake-name": "elegant vintage lively effortless sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2709694", "type": "sweatshirt", "fake-name": "radiant whimsical urban effortless sweatshirt", "image-path": "asset/clothes/sweatshirt/3.jpeg"},
  {
    "item-id": "2034791",
    "type": "sweatshirt",
    "fake-name": "contemporary bohemian sleek trendsetting sweatshirt",
    "image-path": "asset/clothes/sweatshirt/4.jpeg"
  },
  {"item-id": "2842622", "type": "sweatshirt", "fake-name": "classy vibrant refined whimsical sweatshirt", "image-path": "asset/clothes/sweatshirt/3.jpeg"},
  {"item-id": "2010548", "type": "sweatshirt", "fake-name": "glamorous minimalist sleek versatile sweatshirt", "image-path": "asset/clothes/sweatshirt/1.jpeg"},
  {"item-id": "2034791", "type": "sweatshirt", "fake-name": "stylish eclectic zen suave sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2952725", "type": "sweatshirt", "fake-name": "sophisticated playful eclectic suave sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2110905", "type": "sweatshirt", "fake-name": "exquisite radiant graceful urbane sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2952725", "type": "sweatshirt", "fake-name": "chic casual blissful urbane sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2239187", "type": "sweatshirt", "fake-name": "glamorous dynamic zen ethereal sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2759778", "type": "sweatshirt", "fake-name": "polished urban urban trendsetting sweatshirt", "image-path": "asset/clothes/sweatshirt/3.jpeg"},
  {"item-id": "2759778", "type": "sweatshirt", "fake-name": "alluring whimsical regal radiant sweatshirt", "image-path": "asset/clothes/sweatshirt/3.jpeg"},
  {"item-id": "2165820", "type": "sweatshirt", "fake-name": "dapper minimalist eclectic sleek sweatshirt", "image-path": "asset/clothes/sweatshirt/1.jpeg"},
  {"item-id": "2044604", "type": "sweatshirt", "fake-name": "alluring vintage refined bohemian sweatshirt", "image-path": "asset/clothes/sweatshirt/1.jpeg"},
  {"item-id": "2121258", "type": "sweatshirt", "fake-name": "classy minimalist dynamic ethereal sweatshirt", "image-path": "asset/clothes/sweatshirt/3.jpeg"},
  {"item-id": "2010548", "type": "sweatshirt", "fake-name": "classy casual ethereal serene sweatshirt", "image-path": "asset/clothes/sweatshirt/1.jpeg"},
  {"item-id": "2120713", "type": "sweatshirt", "fake-name": "stylish whimsical urban trendsetting sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {
    "item-id": "2110905",
    "type": "sweatshirt",
    "fake-name": "alluring whimsical graceful versatile sweatshirt",
    "image-path": "asset/clothes/sweatshirt/2.jpeg"
  },
  {"item-id": "2120713", "type": "sweatshirt", "fake-name": "striking vintage sharp contemporary sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {
    "item-id": "2487289",
    "type": "sweatshirt",
    "fake-name": "polished bohemian dynamic trendsetting sweatshirt",
    "image-path": "asset/clothes/sweatshirt/2.jpeg"
  },
  {"item-id": "2239187", "type": "sweatshirt", "fake-name": "dapper minimalist eclectic radiant sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2034791", "type": "sweatshirt", "fake-name": "elegant vintage graceful refined sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2709694", "type": "sweatshirt", "fake-name": "chic casual sleek contemporary sweatshirt", "image-path": "asset/clothes/sweatshirt/3.jpeg"},
  {"item-id": "2110905", "type": "sweatshirt", "fake-name": "alluring vibrant refined serene sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {
    "item-id": "2912925",
    "type": "sweatshirt",
    "fake-name": "exquisite whimsical blissful contemporary sweatshirt",
    "image-path": "asset/clothes/sweatshirt/2.jpeg"
  },
  {"item-id": "2842622", "type": "sweatshirt", "fake-name": "chic whimsical wholesome whimsical sweatshirt", "image-path": "asset/clothes/sweatshirt/3.jpeg"},
  {"item-id": "2886456", "type": "sweatshirt", "fake-name": "polished relaxed zen refined sweatshirt", "image-path": "asset/clothes/sweatshirt/1.jpeg"},
  {"item-id": "2120713", "type": "sweatshirt", "fake-name": "fashionable radiant mellow bohemian sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2843943", "type": "sweatshirt", "fake-name": "dapper dynamic spontaneous sleek sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2034791", "type": "sweatshirt", "fake-name": "radiant bohemian zen serene sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2010548", "type": "sweatshirt", "fake-name": "elegant cozy magnetic trendsetting sweatshirt", "image-path": "asset/clothes/sweatshirt/1.jpeg"},
  {
    "item-id": "2616173",
    "type": "sweatshirt",
    "fake-name": "polished playful blissful trendsetting sweatshirt",
    "image-path": "asset/clothes/sweatshirt/2.jpeg"
  },
  {"item-id": "2033787", "type": "sweatshirt", "fake-name": "classy radiant dynamic edgy sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2239187", "type": "sweatshirt", "fake-name": "polished relaxed ethereal organic sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2044604", "type": "sweatshirt", "fake-name": "polished posh mellow refined sweatshirt", "image-path": "asset/clothes/sweatshirt/1.jpeg"},
  {"item-id": "2254449", "type": "sweatshirt", "fake-name": "striking urban ethereal urbane sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2239187", "type": "sweatshirt", "fake-name": "chic bohemian spontaneous refined sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2033787", "type": "sweatshirt", "fake-name": "elegant relaxed regal suave sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2034791", "type": "sweatshirt", "fake-name": "alluring urban sharp radiant sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2034791", "type": "sweatshirt", "fake-name": "edgy relaxed urban sleek sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2952725", "type": "sweatshirt", "fake-name": "dapper vibrant futuristic bohemian sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2709694", "type": "sweatshirt", "fake-name": "trendy dynamic lively organic sweatshirt", "image-path": "asset/clothes/sweatshirt/3.jpeg"},
  {"item-id": "2110905", "type": "sweatshirt", "fake-name": "classy playful blissful urbane sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2185289", "type": "sweatshirt", "fake-name": "chic ethereal magnetic opulent sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2110905", "type": "sweatshirt", "fake-name": "classy minimalist graceful whimsical sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2185289", "type": "sweatshirt", "fake-name": "polished cozy eclectic refined sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2843943", "type": "sweatshirt", "fake-name": "sleek ethereal eclectic sleek sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2709694", "type": "sweatshirt", "fake-name": "classy vintage zen ethereal sweatshirt", "image-path": "asset/clothes/sweatshirt/3.jpeg"},
  {"item-id": "2488571", "type": "sweatshirt", "fake-name": "exquisite urban dynamic organic sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2010548", "type": "sweatshirt", "fake-name": "fashionable quirky zen organic sweatshirt", "image-path": "asset/clothes/sweatshirt/1.jpeg"},
  {"item-id": "2120713", "type": "sweatshirt", "fake-name": "radiant playful urban ethereal sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2185289", "type": "sweatshirt", "fake-name": "fashionable dynamic sleek ethereal sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2842622", "type": "sweatshirt", "fake-name": "chic whimsical free-spirited serene sweatshirt", "image-path": "asset/clothes/sweatshirt/3.jpeg"},
  {"item-id": "2407112", "type": "sweatshirt", "fake-name": "posh urban futuristic sleek sweatshirt", "image-path": "asset/clothes/sweatshirt/1.jpeg"},
  {"item-id": "2842622", "type": "sweatshirt", "fake-name": "fashionable casual mellow refined sweatshirt", "image-path": "asset/clothes/sweatshirt/3.jpeg"},
  {"item-id": "2239187", "type": "sweatshirt", "fake-name": "fashionable cozy sleek effortless sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2044604", "type": "sweatshirt", "fake-name": "alluring playful futuristic ethereal sweatshirt", "image-path": "asset/clothes/sweatshirt/1.jpeg"},
  {"item-id": "2254449", "type": "sweatshirt", "fake-name": "elegant cozy futuristic organic sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2709694", "type": "sweatshirt", "fake-name": "trendy posh eclectic trendsetting sweatshirt", "image-path": "asset/clothes/sweatshirt/3.jpeg"},
  {"item-id": "2254449", "type": "sweatshirt", "fake-name": "dapper whimsical wholesome bohemian sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2185289", "type": "sweatshirt", "fake-name": "classy casual futuristic sleek sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2010548", "type": "sweatshirt", "fake-name": "edgy vintage sleek suave sweatshirt", "image-path": "asset/clothes/sweatshirt/1.jpeg"},
  {"item-id": "2488571", "type": "sweatshirt", "fake-name": "contemporary quirky sleek radiant sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {
    "item-id": "2587162",
    "type": "sweatshirt",
    "fake-name": "contemporary bohemian blissful bohemian sweatshirt",
    "image-path": "asset/clothes/sweatshirt/3.jpeg"
  },
  {"item-id": "2709694", "type": "sweatshirt", "fake-name": "contemporary vintage urban edgy sweatshirt", "image-path": "asset/clothes/sweatshirt/3.jpeg"},
  {"item-id": "2034791", "type": "sweatshirt", "fake-name": "fashionable urban magnetic refined sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2239187", "type": "sweatshirt", "fake-name": "alluring bohemian graceful organic sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2120713", "type": "sweatshirt", "fake-name": "chic whimsical refined edgy sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2044810", "type": "sweatshirt", "fake-name": "edgy radiant wholesome serene sweatshirt", "image-path": "asset/clothes/sweatshirt/3.jpeg"},
  {"item-id": "2488571", "type": "sweatshirt", "fake-name": "trendy dynamic zen serene sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2185289", "type": "sweatshirt", "fake-name": "edgy posh spontaneous whimsical sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2165820", "type": "sweatshirt", "fake-name": "exquisite dynamic urban refined sweatshirt", "image-path": "asset/clothes/sweatshirt/1.jpeg"},
  {"item-id": "2185289", "type": "sweatshirt", "fake-name": "sleek ethereal zen ethereal sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2185289", "type": "sweatshirt", "fake-name": "dapper cozy dynamic urbane sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2843943", "type": "sweatshirt", "fake-name": "sleek radiant spontaneous edgy sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2239187", "type": "sweatshirt", "fake-name": "classy minimalist mellow radiant sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2759778", "type": "sweatshirt", "fake-name": "posh playful lively opulent sweatshirt", "image-path": "asset/clothes/sweatshirt/3.jpeg"},
  {"item-id": "2165820", "type": "sweatshirt", "fake-name": "chic minimalist blissful suave sweatshirt", "image-path": "asset/clothes/sweatshirt/1.jpeg"},
  {
    "item-id": "2587162",
    "type": "sweatshirt",
    "fake-name": "radiant relaxed free-spirited effortless sweatshirt",
    "image-path": "asset/clothes/sweatshirt/3.jpeg"
  },
  {"item-id": "2193444", "type": "sweatshirt", "fake-name": "stylish posh futuristic radiant sweatshirt", "image-path": "asset/clothes/sweatshirt/1.jpeg"},
  {
    "item-id": "2699597",
    "type": "sweatshirt",
    "fake-name": "edgy minimalist eclectic contemporary sweatshirt",
    "image-path": "asset/clothes/sweatshirt/2.jpeg"
  },
  {"item-id": "2842622", "type": "sweatshirt", "fake-name": "striking playful urban suave sweatshirt", "image-path": "asset/clothes/sweatshirt/3.jpeg"},
  {"item-id": "2239187", "type": "sweatshirt", "fake-name": "exquisite eclectic sleek radiant sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2239187", "type": "sweatshirt", "fake-name": "glamorous eclectic sharp effortless sweatshirt", "image-path": "asset/clothes/sweatshirt/4.jpeg"},
  {"item-id": "2912925", "type": "sweatshirt", "fake-name": "exquisite casual blissful versatile sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {
    "item-id": "2185289",
    "type": "sweatshirt",
    "fake-name": "sophisticated dynamic wholesome ethereal sweatshirt",
    "image-path": "asset/clothes/sweatshirt/2.jpeg"
  },
  {"item-id": "2120713", "type": "sweatshirt", "fake-name": "chic quirky spontaneous trendsetting sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2699597", "type": "sweatshirt", "fake-name": "glamorous dynamic magnetic ethereal sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2120713", "type": "sweatshirt", "fake-name": "glamorous minimalist wholesome suave sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2254449", "type": "sweatshirt", "fake-name": "sleek cozy wholesome sleek sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2254449", "type": "sweatshirt", "fake-name": "elegant radiant mellow sleek sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2120713", "type": "sweatshirt", "fake-name": "elegant dynamic eclectic effortless sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {"item-id": "2185289", "type": "sweatshirt", "fake-name": "stylish radiant regal organic sweatshirt", "image-path": "asset/clothes/sweatshirt/2.jpeg"},
  {
    "item-id": "2044604",
    "type": "sweatshirt",
    "fake-name": "exquisite whimsical futuristic organic sweatshirt",
    "image-path": "asset/clothes/sweatshirt/1.jpeg"
  }
];
