final tee_list = [
  {"item-id": "2822800", "type": "tee", "fake-name": "fashionable eclectic sharp trendsetting tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800", "type": "tee", "fake-name": "glamorous posh refined radiant tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800", "type": "tee", "fake-name": "exquisite bohemian wholesome contemporary tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800", "type": "tee", "fake-name": "sleek playful magnetic urbane tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800", "type": "tee", "fake-name": "glamorous urban spontaneous radiant tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800", "type": "tee", "fake-name": "posh relaxed ethereal exuberant tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800", "type": "tee", "fake-name": "sophisticated radiant spontaneous edgy tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800", "type": "tee", "fake-name": "sophisticated dynamic sharp serene tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800", "type": "tee", "fake-name": "stylish quirky eclectic trendsetting tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800", "type": "tee", "fake-name": "contemporary relaxed graceful organic tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800", "type": "tee", "fake-name": "posh relaxed zen refined tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800", "type": "tee", "fake-name": "sophisticated posh sharp refined tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800", "type": "tee", "fake-name": "sleek bohemian ethereal trendsetting tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800", "type": "tee", "fake-name": "trendy vintage regal trendsetting tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800", "type": "tee", "fake-name": "dapper posh graceful opulent tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800", "type": "tee", "fake-name": "radiant bohemian magnetic poised tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800", "type": "tee", "fake-name": "fashionable bohemian eclectic trendsetting tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800", "type": "tee", "fake-name": "exquisite vintage spontaneous serene tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800", "type": "tee", "fake-name": "fashionable quirky futuristic suave tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800", "type": "tee", "fake-name": "dapper urban blissful edgy tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800", "type": "tee", "fake-name": "radiant relaxed free-spirited serene tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800", "type": "tee", "fake-name": "edgy minimalist ethereal suave tee", "image-path": "asset/clothes/tee/1.jpeg"}
];
