final tee_list = [
  {"item-id": "2822800_14", "type": "tee", "fake-name": "polished bohemian blissful organic tee", "image-path": "asset/clothes/tee/3.jpeg"},
  {"item-id": "2822800_8", "type": "tee", "fake-name": "posh ethereal regal ethereal tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800_20", "type": "tee", "fake-name": "fashionable relaxed lively poised tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800_8", "type": "tee", "fake-name": "posh ethereal regal ethereal tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800_8", "type": "tee", "fake-name": "posh ethereal regal ethereal tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800_8", "type": "tee", "fake-name": "posh ethereal regal ethereal tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800_20", "type": "tee", "fake-name": "fashionable relaxed lively poised tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800_14", "type": "tee", "fake-name": "polished bohemian blissful organic tee", "image-path": "asset/clothes/tee/3.jpeg"},
  {"item-id": "2822800_8", "type": "tee", "fake-name": "posh ethereal regal ethereal tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800_14", "type": "tee", "fake-name": "polished bohemian blissful organic tee", "image-path": "asset/clothes/tee/3.jpeg"},
  {"item-id": "2822800_8", "type": "tee", "fake-name": "posh ethereal regal ethereal tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800_8", "type": "tee", "fake-name": "posh ethereal regal ethereal tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800_4", "type": "tee", "fake-name": "striking dynamic sharp whimsical tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800_14", "type": "tee", "fake-name": "polished bohemian blissful organic tee", "image-path": "asset/clothes/tee/3.jpeg"},
  {"item-id": "2822800_14", "type": "tee", "fake-name": "polished bohemian blissful organic tee", "image-path": "asset/clothes/tee/3.jpeg"},
  {"item-id": "2822800_14", "type": "tee", "fake-name": "polished bohemian blissful organic tee", "image-path": "asset/clothes/tee/3.jpeg"},
  {"item-id": "2822800_8", "type": "tee", "fake-name": "posh ethereal regal ethereal tee", "image-path": "asset/clothes/tee/1.jpeg"},
  {"item-id": "2822800_8", "type": "tee", "fake-name": "posh ethereal regal ethereal tee", "image-path": "asset/clothes/tee/1.jpeg"}
];
