final trench_list = [
  {"item-id": "2954118_4", "type": "trench", "fake-name": "polished bohemian blissful organic trench", "image-path": "asset/clothes/trench/1.jpeg"},
  {"item-id": "2954118_14", "type": "trench", "fake-name": "sophisticated playful refined urbane trench", "image-path": "asset/clothes/trench/3.jpeg"},
  {"item-id": "2954118_8", "type": "trench", "fake-name": "classy vintage zen versatile trench", "image-path": "asset/clothes/trench/1.jpeg"},
  {"item-id": "2954118_20", "type": "trench", "fake-name": "chic casual eclectic opulent trench", "image-path": "asset/clothes/trench/1.jpeg"},
  {"item-id": "2954118_14", "type": "trench", "fake-name": "sophisticated playful refined urbane trench", "image-path": "asset/clothes/trench/3.jpeg"},
  {"item-id": "2954118_8", "type": "trench", "fake-name": "classy vintage zen versatile trench", "image-path": "asset/clothes/trench/1.jpeg"},
  {"item-id": "2954118_8", "type": "trench", "fake-name": "classy vintage zen versatile trench", "image-path": "asset/clothes/trench/1.jpeg"},
  {"item-id": "2954118_4", "type": "trench", "fake-name": "polished bohemian blissful organic trench", "image-path": "asset/clothes/trench/1.jpeg"},
  {"item-id": "2954118_14", "type": "trench", "fake-name": "sophisticated playful refined urbane trench", "image-path": "asset/clothes/trench/3.jpeg"},
  {"item-id": "2954118_14", "type": "trench", "fake-name": "sophisticated playful refined urbane trench", "image-path": "asset/clothes/trench/3.jpeg"},
  {"item-id": "2954118_20", "type": "trench", "fake-name": "chic casual eclectic opulent trench", "image-path": "asset/clothes/trench/1.jpeg"},
  {"item-id": "2954118_4", "type": "trench", "fake-name": "polished bohemian blissful organic trench", "image-path": "asset/clothes/trench/1.jpeg"},
  {"item-id": "2954118_4", "type": "trench", "fake-name": "polished bohemian blissful organic trench", "image-path": "asset/clothes/trench/1.jpeg"},
  {"item-id": "2954118_14", "type": "trench", "fake-name": "sophisticated playful refined urbane trench", "image-path": "asset/clothes/trench/3.jpeg"},
  {"item-id": "2954118_8", "type": "trench", "fake-name": "classy vintage zen versatile trench", "image-path": "asset/clothes/trench/1.jpeg"},
  {"item-id": "2954118_14", "type": "trench", "fake-name": "sophisticated playful refined urbane trench", "image-path": "asset/clothes/trench/3.jpeg"},
  {"item-id": "2954118_14", "type": "trench", "fake-name": "sophisticated playful refined urbane trench", "image-path": "asset/clothes/trench/3.jpeg"},
  {"item-id": "2954118_4", "type": "trench", "fake-name": "polished bohemian blissful organic trench", "image-path": "asset/clothes/trench/1.jpeg"},
  {"item-id": "2954118_14", "type": "trench", "fake-name": "sophisticated playful refined urbane trench", "image-path": "asset/clothes/trench/3.jpeg"},
  {"item-id": "2954118_14", "type": "trench", "fake-name": "sophisticated playful refined urbane trench", "image-path": "asset/clothes/trench/3.jpeg"}
];
