final turtleneck = [
  {"item-id": "2292972", "type": "turtleneck", "fake-name": "edgy dynamic sharp sleek turtleneck", "image-path": "asset/clothes/turtleneck/1.jpeg"},
  {"item-id": "2244325", "type": "turtleneck", "fake-name": "glamorous casual urban ethereal turtleneck", "image-path": "asset/clothes/turtleneck/2.jpeg"},
  {"item-id": "2040702", "type": "turtleneck", "fake-name": "sleek urban regal suave turtleneck", "image-path": "asset/clothes/turtleneck/3.jpeg"},
  {"item-id": "2244325", "type": "turtleneck", "fake-name": "polished urban graceful serene turtleneck", "image-path": "asset/clothes/turtleneck/2.jpeg"},
  {"item-id": "2126992", "type": "turtleneck", "fake-name": "exquisite quirky wholesome exuberant turtleneck", "image-path": "asset/clothes/turtleneck/1.jpeg"},
  {"item-id": "2292972", "type": "turtleneck", "fake-name": "trendy eclectic futuristic poised turtleneck", "image-path": "asset/clothes/turtleneck/1.jpeg"},
  {"item-id": "2244325", "type": "turtleneck", "fake-name": "chic urban free-spirited refined turtleneck", "image-path": "asset/clothes/turtleneck/2.jpeg"},
  {"item-id": "2126992", "type": "turtleneck", "fake-name": "sleek posh mellow ethereal turtleneck", "image-path": "asset/clothes/turtleneck/1.jpeg"},
  {"item-id": "2126992", "type": "turtleneck", "fake-name": "striking eclectic magnetic ethereal turtleneck", "image-path": "asset/clothes/turtleneck/1.jpeg"},
  {"item-id": "2292972", "type": "turtleneck", "fake-name": "striking quirky lively whimsical turtleneck", "image-path": "asset/clothes/turtleneck/1.jpeg"},
  {"item-id": "2244325", "type": "turtleneck", "fake-name": "stylish relaxed urban effortless turtleneck", "image-path": "asset/clothes/turtleneck/2.jpeg"},
  {"item-id": "2040702", "type": "turtleneck", "fake-name": "glamorous dynamic zen exuberant turtleneck", "image-path": "asset/clothes/turtleneck/3.jpeg"},
  {"item-id": "2126992", "type": "turtleneck", "fake-name": "alluring ethereal refined urbane turtleneck", "image-path": "asset/clothes/turtleneck/1.jpeg"},
  {
    "item-id": "2040702",
    "type": "turtleneck",
    "fake-name": "elegant minimalist ethereal exuberant turtleneck",
    "image-path": "asset/clothes/turtleneck/3.jpeg"
  },
  {"item-id": "2126992", "type": "turtleneck", "fake-name": "sleek relaxed graceful effortless turtleneck", "image-path": "asset/clothes/turtleneck/1.jpeg"},
  {"item-id": "2126992", "type": "turtleneck", "fake-name": "trendy posh graceful versatile turtleneck", "image-path": "asset/clothes/turtleneck/1.jpeg"},
  {"item-id": "2244325", "type": "turtleneck", "fake-name": "posh whimsical dynamic exuberant turtleneck", "image-path": "asset/clothes/turtleneck/2.jpeg"},
  {"item-id": "2292972", "type": "turtleneck", "fake-name": "polished urban blissful effortless turtleneck", "image-path": "asset/clothes/turtleneck/1.jpeg"},
  {"item-id": "2292972", "type": "turtleneck", "fake-name": "classy minimalist eclectic poised turtleneck", "image-path": "asset/clothes/turtleneck/1.jpeg"},
  {"item-id": "2244325", "type": "turtleneck", "fake-name": "fashionable dynamic regal radiant turtleneck", "image-path": "asset/clothes/turtleneck/2.jpeg"},
  {"item-id": "2040702", "type": "turtleneck", "fake-name": "exquisite casual dynamic versatile turtleneck", "image-path": "asset/clothes/turtleneck/3.jpeg"},
  {"item-id": "2244325", "type": "turtleneck", "fake-name": "sleek whimsical spontaneous radiant turtleneck", "image-path": "asset/clothes/turtleneck/2.jpeg"},
  {"item-id": "2126992", "type": "turtleneck", "fake-name": "edgy posh sleek sleek turtleneck", "image-path": "asset/clothes/turtleneck/1.jpeg"},
  {"item-id": "2126992", "type": "turtleneck", "fake-name": "trendy dynamic free-spirited sleek turtleneck", "image-path": "asset/clothes/turtleneck/1.jpeg"},
  {"item-id": "2126992", "type": "turtleneck", "fake-name": "alluring posh regal poised turtleneck", "image-path": "asset/clothes/turtleneck/1.jpeg"},
  {"item-id": "2244325", "type": "turtleneck", "fake-name": "striking radiant mellow versatile turtleneck", "image-path": "asset/clothes/turtleneck/2.jpeg"},
  {"item-id": "2244325", "type": "turtleneck", "fake-name": "polished playful blissful bohemian turtleneck", "image-path": "asset/clothes/turtleneck/2.jpeg"},
  {"item-id": "2292972", "type": "turtleneck", "fake-name": "edgy vintage zen radiant turtleneck", "image-path": "asset/clothes/turtleneck/1.jpeg"},
  {"item-id": "2126992", "type": "turtleneck", "fake-name": "trendy minimalist magnetic opulent turtleneck", "image-path": "asset/clothes/turtleneck/1.jpeg"},
  {"item-id": "2244325", "type": "turtleneck", "fake-name": "sophisticated whimsical mellow sleek turtleneck", "image-path": "asset/clothes/turtleneck/2.jpeg"},
  {"item-id": "2126992", "type": "turtleneck", "fake-name": "alluring dynamic wholesome ethereal turtleneck", "image-path": "asset/clothes/turtleneck/1.jpeg"},
  {"item-id": "2126992", "type": "turtleneck", "fake-name": "dapper minimalist blissful opulent turtleneck", "image-path": "asset/clothes/turtleneck/1.jpeg"},
  {"item-id": "2554446", "type": "turtleneck", "fake-name": "striking posh refined refined turtleneck", "image-path": "asset/clothes/turtleneck/3.jpeg"},
  {"item-id": "2040702", "type": "turtleneck", "fake-name": "chic cozy futuristic effortless turtleneck", "image-path": "asset/clothes/turtleneck/3.jpeg"}
];
